<!DOCTYPE html>

<?php
$globalNavId = "newsletters";
?>

<html lang="en">

<head>
<meta name="keywords" content="General Principles, San Shou, Kuai Jiao, Part 3, Coordination, Internal, Grandmaster Shou-Yu Liang, Tai D. Ngo" />
<meta name="description" content="General Principles of San Shou Kuai Jiao - Part 3, Coordination of the Internal, By Grandmaster Shou-Yu Liang and Tai D. Ngo" />
<title>General Principles of San Shou Kuai Jiao - Part 3, Coordination of the Internal - shouyuliang.com</title>
<?php include "../../ssi/meta.php"; ?>
</head>

<body>

<?php include "../../ssi/header.php"; ?>

<div id="syl-body-bkg">
  <div id="syl-body">
    <div id="syl-body1">
      <div class="contentWidth clearfix">
        <nav id="syl-breadcrumb" class="breadcrumbs pathway">
          	<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/newsletters/" class="pathway">Articles</a> <img src="/templates/syl/images/arrow.png" /> <a href="index.php" class="pathway">2007 March/April</a> <img src="../../templates/syl/images/arrow.png" /> General Principles of San Shou Kuai Jiao - Part 3, Coordination of the Internal
        </nav>
		<article>
	        <h1 class="contentheading">General Principles of San Shou Kuai Jiao - Part 3, Coordination of the Internal</h1>
	        <h2>By Grandmaster Shou-Yu Liang and Tai D. Ngo</h2>
	        <br><br>
			<h3>Coordination of the Internal</h3>
			<br />
			<div class="articleImage"><img src="../../images/newsletter/v7n2/a6p1.jpg" width="300" height="224" border="0" alt="Paul vs Derek - Throw"><br />Paul vs Derek - Throw</div>
			<p><b>Essence (Jing)</b></p>
			<p>Jing means essence, the most refined organic material in your body, which you inherited from your parents. In fact, it is the Jing which decides how strong and healthy you will be. Chinese medicine believes human Jing is stored in the kidneys. When the Jing is abundant and of good quality, you will have a strong physical body, abundant Qi, and a high spirit. Therefore, learning how to conserve your essence has been an important part of Chinese martial arts training. There are a few things that may affect the storage of your essence.</p>
			<ol type="1">
				<li>Too much sex. This applies to males. According to Chinese medicine, when a man engages in too much sexual activity, his kidneys will be overworked and the production of the essence to supply the body's needs will be significantly reduced. Therefore, a martial artist must learn to regulate his sex life. It has also been discovered in Chinese martial arts society that if a man has sex before combat, his energy and endurance will be low and he can easily be defeated.</li>
				<li>Too much training without rest. A smart martial artist will know how to train hard but also know how to relax and allow his body to recover. When a body is over-exercised, the kidneys and liver will be too Yang, or too positive, which can result in physical and mental fatigue. When this happens, you will not be able to keep your mental center in the fight. Consequently, your spirit will be low and your judgment poor.</li>
				<li>Unhealthy lifestyle. Another way to damage the storage and the manifestation of the essence is a poor lifestyle-excessive drinking, smoking, a lack of sleep, and poor eating habits. When this happens, both the physical and spiritual body will be affected, and your Qi will also be weak and deficient.</li>
			</ol>
			<p>Therefore, in order to perform your martial skill effectively and efficiently, the first thing you should concern yourself with is how to preserve and protect your essence. Essence (Jing), Spirit (Shen), and Internal Energy (Qi) are considered the three treasures (San Bao) in Chinese Qigong and martial arts society.</p>
			<p><b>Spirit (Shen)</b></p>
			<p>Shen is spirit, or morale. When your spirit is high, your fighting techniques can be executed skillfully and powerfully. In Chinese Qigong society, it is believed that it is the essence stored in the body which makes the production of Qi strong (Lian Jing Hua Qi). When the Qi is abundant and circulating strongly, the Qi can be led to the brain to raise the spirit, which can strengthen your will and motivation.</p>
			<p>It is because of this reason that Jing-Shen (Essence-Spirit) is commonly used together and referred to as the "spirit of vitality." It also reflects the energy (Qi) level of your body. When your spirit is high the Qi can be directed efficiently to energize the physical body to its maximum.</p>
			<p>Learning how to raise your spirit of vitality is an important part of Chinese martial arts training. When your spirit is high, you will be brave and confident. It is said: "Yi Dan, Er Li, San Gongfu". This means: "First, bravery; second, power; and third, technique." From this, you can see bravery, generated by a high spirit (fighting morale), is the most important element for a martial artist to have.</p>
			<p>To conclude, when your spirit is high it will reflect externally in your face and eyes, which shows your opponent your confidence and bravery. Therefore, when you encounter an opponent, you must first raise your spirit yet remain calm. Physically, when your spirit is high your Qi is abundant and able to energize the muscles and tendons to their maximum efficiency. When this happens, your body will become more agile, speedy, and powerful.</p>
			<p><b>Internal Energy (Qi)</b></p>
			<p>As mentioned earlier, Qi is one of the three treasures for maintaining your life force. Qi generally refers to universal energy, and also to the energy circulating in human and animal bodies. To Chinese martial artists, Qi is the root and foundation of physical strength. Through correct breathing training and mental concentration, Qi can be built up to a stronger and more abundant level in the Lower Dan Tian (Xia Dan Tian). When this internal energy is sent to the external physical body, it becomes martial power (Jin) and significantly improves the effectiveness of the techniques you execute.</p>
			<p>When you encounter an opponent, you must keep your mind calm and breathe naturally. Use reverse breathing to sink your Qi to the Lower Dan Tian to prevent your body and mind from getting too excited, which can result in shallow breathing. When you are excited and breathe shallowly, your Qi will rise upward and become weak. In this case, your root will also be shallow, making it easier for your opponent to throw you down.</p>
			<p>In addition, when you are excited and breathing fast, you will become fatigued and lose your endurance. In order to maintain your endurance and keep your fighting spirit high, you must learn how to use and control your Qi efficiently. When this internal energy is manipulated properly, it will maximize your physical strength. To learn more about Qi and Qigong, especially for martial purposes, refer to the book <a href="http://www.amazon.com/gp/redirect.shtml?ie=UTF8&location=http%3A%2F%2Fwww.amazon.com%2FEssence-Shaolin-White-Crane-Martial-Qigong%2Fdp%2F1886969353%3Fie%3DUTF8%26s%3Dbooks%26qid%3D1189144497%26sr%3D8-1&tag=theofficiasho-20&linkCode=ur2&camp=1789&creative=9325">The Essence of Shaolin White Crane</a><img src="http://www.assoc-amazon.com/e/ir?t=theofficiasho-20&l=ur2&o=1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, by Dr. Yang, Jwing-Ming.</p>
			<p><b>Power/Strength (Li)</b></p>
			<p>The general understanding of Li is muscular power (force) generated by the physical body. It also implies the martial power (Jin, 0) of martial arts training. Jin is generally defined as martial power in which your physical body is energized by Qi and the spirit to its maximum efficiency and potential. All Chinese martial arts styles train Jin. Although there are many different ways of Jin training in Chinese martial arts, its theory and principles remain the same.</p>
			<p>In order to make the San Shou Kuai Jiao techniques effective and powerful, you must also train Jin. There are many different kinds of San Shou Kuai Jiao Jin training. For example: Inch Jin (Cun Jin), Explosive Jin (Bao Fa Jin), Extend/Stretch Jin (Beng Jin, A 0), Ingenuity Jin (Qiao Jin), Penetrate/ Thrusting Jin (Tong Jing), Twisting Jin (Ning Jin), etc. When Jin is properly applied to a technique, the technique becomes more powerful and alive.</p>
			<p>A proficient martial artist should always avoid using Jin directly against an opponent's Jin. You should be able to manifest Jin naturally, and either as hard or as soft as necessary. When the Jin is too hard, the power will not be alive and smooth and can be easily neutralized by your opponent. If it is too soft, then the power will not be strong enough to execute the technique effectively and powerfully. Some Jin training methods will be introduced in chapter 2 and chapter 3 of this book. For more information on Jin training, refer to the book <a href="http://www.amazon.com/gp/product/1886969434?ie=UTF8&tag=theofficiasho-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1886969434">Tai Chi Theory & Martial Power, by Dr. Yang, Jwing-Ming.</a><img src="http://www.assoc-amazon.com/e/ir?t=theofficiasho-20&l=as2&o=1&a=1886969434" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /></p>
			<p><b>Gongfu/Kung Fu (Gong)</b></p>
			<p>Gong generally refers to the level of martial skill attained by the martial artist. It includes body conditioning, internal mind and Qi cultivation, martial techniques, and power. In some styles, Gong often refers to special skill levels which take a great effort of energy and time to train. Therefore, Gong has been commonly used to measure the level of effectiveness and strength of the power in martial techniques.</p>
			<p>Gongfu/Kung Fu literally means "energy-time." It also refers to any study, learning, or practice which requires patience, energy, and time to learn or accomplish. Since practicing Chinese martial arts requires a great deal of time and energy, Chinese martial arts are also commonly called Gongfu.</p>
			<p>To become a proficient San Shou Kuai Jiao expert, your San Shou Kuai Jiao Gongfu level must be excellent in all areas-technique, speed, power, spirit, etc. When your opponent is fast, you must be faster. When your opponent is powerful, you should be stronger, fiercer, and more skillful. Your endurance should be superior. In all, your Gongfu (basic body and mental conditioning and skills) has to be of the highest level in order to win. Keep practicing basic skills diligently and you will make your San Shou Kuai Jiao Gongfu more proficient.</p>
		</article>
      </div>
    </div>
  </div>
</div>

<?php include "../../ssi/footer.php"; ?>

</body>

</html>