<!DOCTYPE html>

<?php
$globalNavId = "newsletters";
?>

<html lang="en">

<head>
<meta name="keywords" content="Essence, Baguazhang, Translation, Ancient Secrets, Thirty-Six, Forty-Eight, Songs, Grandmaster Shou-Yu Liang, Dr. Jwing-Ming Yang, Master Wen-Ching Wu" />
<meta name="description" content="The Essence of Baguazhang - Translation of Ancient Secrets - Baguazhang Thirty-Six and Forty-Eight Songs, By Grandmaster Shou-Yu Liang, Dr. Jwing-Ming Yang, and Master Wen-Ching Wu" />
<title>The Essence of Baguazhang - Translation of Ancient Secrets - Baguazhang Thirty-Six and Forty-Eight Songs - shouyuliang.com</title>
<?php include "../../ssi/meta.php"; ?>
</head>

<body>

<?php include "../../ssi/header.php"; ?>

<div id="syl-body-bkg">
  <div id="syl-body">
    <div id="syl-body1">
      <div class="contentWidth clearfix">
        <nav id="syl-breadcrumb" class="breadcrumbs pathway">
          	<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/newsletters/" class="pathway">Articles</a> <img src="/templates/syl/images/arrow.png" /> <a href="index.php" class="pathway">2006 September/October</a> <img src="../../templates/syl/images/arrow.png" /> The Essence of Baguazhang - Translation of Ancient Secrets - Baguazhang Thirty-Six and Forty-Eight Songs
        </nav>
		<article>
	        <h1 class="contentheading">The Essence of Baguazhang - Translation of Ancient Secrets - Baguazhang Thirty-Six and Forty-Eight Songs</h1>
	        <h2>By Grandmaster Shou-Yu Liang, Dr. Jwing-Ming Yang, and Master Wen-Ching Wu</h2>
	        <br><br>
			<h3>Baguazhang Thirty-Six and Forty-Eight Secret Songs</h3>
			<br />
			<img src="../../images/newsletter/v6n4/a1p1.jpg" width="300" height="225" border="0" alt="Helen Liang - Bagua Deer Hooks" align="right" style="margin:0px 0px 10px 10px;">
			<p>In Baguazhang, there are two sets of secret songs which are said to have been passed down by Master Dong Hai-Chuan. The first set includes 36 songs for Baguazhang beginners, and the second set has 48 songs for advanced practitioners. It is widely believed and acknowledged that these songs are the essence of the Baguazhang. In this section, we will translate these two sets of songs and offer some commentary. First however, we would like to translate a short song which appraises these two sets of songs.</p>
			<h4>Song of Appraise</h4>
			<blockquote>The meaning of the 36 songs is real and accurate. (If one) only talks and talks, practices and practices, (then he) will not be able to reach its spirit (essence). (If) wish to obtain these secrets and achieve the real Kung Fu, one will have to spend (at least) three years to experience its depth.</blockquote>
			<p>The contents of the 36 songs are the real essence of the Baguazhang art. If you simply talk about it and practice without placing all your spiritual effort into it, you will never reach the essence of the art. If your goal is to reach the higher levels, you will need at least three years of hard practice to experience the real spirit of the art.</p>
			<blockquote>It is very difficult to reach (the final goals of) the 48 techniques. When these techniques are used, they cannot be applied freely (i.e., naturally and comfortably). (Only after spending) ten years of refined study and research, a single person's martial techniques can compete on the five continents.</blockquote>
			<p>From this song you can see that the 36 songs are mainly for beginners, and you will need about three years of serious study for successful training. However, in order to reach the higher levels of the Baguazhang skill, you must again spend at least ten years of refined study on the 48 songs.</p>
			<h4>36 Secret Songs of Baguazhang</h4>
			<blockquote>Empty the chest, pull (up) the head, and settle down the waist. Firm the thighs, control the knees, and grab the ground strongly. Sink the shoulders, drop the elbows, and extend the front palm. Both eyes must look out through the tiger's mouth.</blockquote>
			<p>This first song is talking about the basic Baguazhang postures. The chest should cave in (i.e. be held in comfortably), the head should be suspended, and the waist should be relaxed and the body should be upright, with the back straight. In order to have a strong stance, the thighs should be squeezed slightly inward, the knees should be strongly locked, and the feet should "grab" the ground tightly. The shoulders and the elbows should be sunk. The front palm should extend forward and the four fingers (except the thumb) should point upward. All the fingers should be opened. The eyes look forward through the space between the thumb and the index finger (i.e., tiger's mouth).</p>
			<p>When you have accomplished this basic posture, then your stance and walking will be firm and rooted. Your chest will be loose for breathing, your abdomen will be relaxed, and the Qi can be full. When you focus your view through the tiger's mouth, you can focus your mind forward. and build up your sense of enemy.</p>
			<blockquote>The rear elbow first folds and it covers the heart. The hands then turn and collapse (i.e., settle the wrist) to follow the front. Follow to the front elbow with the embracing power. Both the front and the rear hands have a sole gathered Shen (spirit).</blockquote>
			<p>This song is talking about the posture of the arms. The rear elbow should bend and protect the center of the body. The fingers of both hands should turn so that they point upward (except the thumbs), and the wrists should be collapsed and settled. The rear arm follows the front arm to its elbow area and extends forward. As you do this, both the arms and the chest should suggest an encircling, embracing energy pattern. Though the front and rear arms are separated, the spirit that directs them is one. This means both arms coordinate with each other and with a single heart.<p>
			<blockquote>Step with curve and extend forward with straight leg. (When) walking (the body) is erect like pushing a grindstone. Bend the knees and follow (i.e., coordinate and match with) the thighs, the waist must be sufficiently twisted. The eyes reach the three directions without swaying the body.</blockquote>
			<p>This song is talking about stepping. While practicing Baguazhang, you walk in a circle.</p>
			<p>When you step, the feet should curve inward. In addition, when you walk your stepping leg should be straight and extended forward. Walking should be firm and rooted as if you were pushing a grindstone. Your knees must bend slightly, and should be completely coordinated with the thighs and waist. When you walk in this posture, even if your eyes watch the three directions (i.e., left, right, and front), you are stable, centered and balanced, without shaking.</p>
			<blockquote>(Grabbing the secret of) the sole posture of "Single whip" is not marvelous. It is appropriate that (if you can apply it) left and right repeatedly. (If you can) change the left to right and right to left, (then you may) withdraw the body and step backward at the proper opportunity.</blockquote>
			<p>This song explains the importance of left and right technique exchanges. Even if you have grasped the secrets of movement and the applications of a single form, it is not marvelous. You should be able to exchange this technique, and skillfully apply it from the left side to the right, and vice versa. Then, when you advance or retreat you will feel natural, easy, and comfortable. This song means that in combat, you should be able to skillfully apply any technique.</p>
			<blockquote>The steps turn and the hands follow (i.e., coordinate with the stepping). The rear palm bores out and the front palm returns. To and fro, fro and to, without two goals. (It) must be like an arrow on a crossbow leaving the string.</blockquote>
			<p>This song is talking about the coordination of the hands and feet. When your stepping is turning, your hands follow and change back and forth. The rear palm bores forward and the front palm withdraws. When you exchange your palms, they both act the same, fast and accurate, just like an arrow fired from a crossbow.</p>
			<blockquote>When boring, the palm moves straight forward closely along the elbow. The rear shoulder will take the place of the front shoulder. Do not separate and do not hesitate. The foot enters the (opponent's) thighs is the correct rule (i.e., right way).</blockquote>
			<p>This song describes the keys of the boring palm. When your palm is boring forward, the fingers of the palm also point forward and closely follow the elbow of the other arm. Once the palms exchange their positions, the rear shoulder becomes the front shoulder, taking over the front shoulder's responsibilities. When you exchange arms, you should not hesitate and the movements of both palms should be closely coordinated. An important key to Baguazhang strategy is to gain an advantageous position by stepping your foot into the space between your opponent's legs. Doing this is called entering and occupying your opponent's empty door.</p>
			<blockquote>The chest must be empty and the Qi is led to sink (to the Dan Tian). The back is tight, the shoulders are dropped, and the arms are extended forward. (When) Qi is led to Dan Tian, the "Grain path" is withdrawn. Pull the head straight upward to fill up the spirit of vitality.</blockquote>
			<p>This song is talking about how to transport the Qi. First, you should relax your chest area, which allows air to be taken in easily. When the front of your body is loose, the Qi can easily be led to the Lower Dan Tian. The back should be arced, the shoulders should be dropped, and the arms should extend forward. When you inhale to lead the Qi to Lower Dan Tian, the grain path (i.e., anus) should be withdrawn (i.e., you use reverse breathing). In Chinese martial arts, to store your Jin, first you must store your Yi. The coordination of reverse breathing enables you to lead the Qi to the Lower Dan Tian while inhaling. When you store your Jin, the anus is gently held upward; exhale and expand your anus as you emit your Jin. This allows the Qi to be led easily to the extremities to support your physical power. Whenever you store or emit your Jin, be sure to keep your head upright, and your spirit of vitality raised.</p>
			<blockquote>When (you) walk, the entire body should not sway. All (of this) relies on the two (calves) under the knees crossing each other (firmly). Though the (stability) of the lower section (of the body) concerns the balanced waist and thighs, the middle section (of the body) also needs the legs and waist.</blockquote>
			<p>This song refers to the means for keeping the body steady and firm while walking. When the body is discussed in Chinese martial society, it is normally divided into three sections. These three sections are called "San Pan" (three sections). San Pan includes the lower section (Xia Pan) from the knees down to the feet, the middle section (Zhong Pan) from the knees up to the solar plexus, and the upper section (Shang Pan) from the solar plexus up to the head.</p>
			<p>This song says when you are walking, the middle and upper sections should be stable and not sway around. All motion depends on the lower section, which is below the knees. In order to have stable stepping, the waist and the thighs (i.e., middle section of the body) must be balanced. Even then, the balance of the middle section still depends on how the waist and legs coordinate with each other.</p>
			<blockquote>Kiss (i.e., Lightly touch) the lips, close the mouth, the tongue touches the roof of the mouth. In the breathing, (the air is) all entered from the nose. When manifesting the Li to its maximum, use the Hen and Ha sounds to emit. Unite the whole Original Qi as one; it is called "Gaining."</blockquote>
			<p>This song talks about how to manifest the Qi from your physical body in order to maximize its power. Baguazhang uses reverse breathing. When you inhale, the Qi is sunk to the Lower Dan Tian, and the anus is withdrawn. When you exhale, the Qi is led to the muscles to energize them, and the anus is pushed out slightly. When you manifest your Qi into Jin, your tongue should always touch the roof of the mouth, connecting the Conceptional and Governing Vessels. When you inhale or exhale, the air enters and exits from the nose. In order to maximize your Jin, "Hen" and "Ha" sounds should be used. Only after you grasp this key - uniting the entire body's Original Qi and manifesting it into Jin - can you say you have gained the secret. If you are interested in knowing more about "Hen" and "Ha" sounds, please refer to Advanced Yang Style Tai Chi Chuan - Vol. 1, by YMAA.</p>
			<blockquote>The shapes of the palms and the tiger mouth areas should be extended and round. The gaps between the ten fingers - (especially) the ring finger - must be opened and extended. First poke, then strike using the wrist bone. Loosen the shoulders and grow the waist, drill in following the stepping.</blockquote>
			<p>This song discusses the shape of the palm. The palms and the place between the thumb and the second finger (tiger mouth) should be round and extended like holding a ball. All ten fingers should be extended. When you use the hand to strike, the fingers point forward as if you are poking. Then settle the wrist, making the fingers point upward (Zuo Wan), in order to use the bottom of the palm to strike. When you use the palm to strike, the shoulders should be loose and the body extended (i.e., growing waist). Follow with a step, drilling into the opponent's body.</p>
			<blockquote>Step forward with closed knees and step backward with controlled (root). (When) exchanging the palms and exchanging the stepping, the body skeleton should be low. Forward and retreat, retreat and forward according to the opportunity. This can be skillfully arranged merely with the waist and the thighs.</blockquote>
			<p>This song is talking about body movements. When you step forward and backward, the knees are closed, not wide open. Only then will your stepping be firm and rooted. When you exchange your palms while stepping, your body's posture should be low. The timing of advances and retreats depends on the situation and available opportunities. Success is decided only by how skillfully you can move your waist and thighs.</p>
			<blockquote>This palm (i.e., Baguazhang) has a great difference from others. Stepping forward with moving front (leg first) is able to achieve success. Still, (when) stepping backward, the rear foot should retreat first. (When) stepping, try to keep on the outside (of the opponent) and away from the center (line).</blockquote>
			<p>This song talks about stepping. Baguazhang is very different from other martial styles for many reasons, but primarily for the stepping patterns it uses. For example, when you step forward in Baguazhang, you must move your front leg first, and when you retreat you must step with your rear foot first. Only then will your stepping be firm and rooted. In addition, when you step either forward or backward, you should keep away from the center line between you and your opponent. This center line is most dangerous while your are moving.</p>
			<blockquote>This palm (i.e., Baguazhang) has a great difference from others. Before moving the hands, first the thighs attack. Before extending forward, first withdraw backward. (When) withdraw enough then emit, the effort is only half.</blockquote>
			<p>This song discusses the way Jin is stored. Before you attack with your hands, you first firm your root with your thighs. Only with this firm root can the power be strong. However, before you emit your Jin, you must first store it. When you can store and emit your Jin skillfully, you will be able to generate great power.</p>
			<blockquote>This palm (i.e., Baguazhang) has a great difference from others. The power (Li of the front palm and the rear palm is connected. (If you) wish to use the endings, first move it's root. Every form like this do not treat lightly.</blockquote>
			<p>This song is talking about the way of emitting Jin. One of the most important keys of emitting Jin in Baguazhang is that all of the strikes start from their roots. For example, the shoulders are the root of the hands and the feet are the roots of the body. In addition, the front and rear hands must be coordinated and act as a single unit. When you practice according to these rules, all of your manifestations of Jin will be rooted and powerful.</p>
			<blockquote>This palm (i.e., Baguazhang) has a great difference from others. Before striking the west, first attack the east. Pointing upward and strike downward, nobody is able to know. Rolling the pearl and reversing the current are more supernatural ubiquitously.</blockquote>
			<p>This song talks about palm usage. When you use the palms to attack, your opponent does not know where you are going to strike. In Baguazhang, the palms can look like they are striking forward when they are actually withdrawing backward. It may seem like you are striking upward, but instead you are attacking downward. Substantial seems like insubstantial and insubstantial looks like substantial. Moreover, if you are able to move and turn your palms skillfully - like a rolling pearl - and move forward and backward, your palms like a flowing current, then your opponent will be unable to figure out your intention and strategy.</p>
			<blockquote>(Even) the natural refined techniques (i.e., skillful martial techniques) are afraid (of the) three "Borings." If not walk from external door, it is still in vain. (If) the opponent walks from outside, I walk inside. (Then) it is not difficult to extend my hand and gain.</blockquote>
			<p>A good martial artist will practice his techniques until they are natural and refined. Even higher level martial artists still are afraid of the three "Boring" (San Chuan) techniques in Baguazhang. "San Chuan" is one of the key techniques in Baguazhang, and when it is used to attack continuously, it cam defeat many good martial arts experts. However, even if you use "San Chuan" but do not know how ft enter the opponent's defended area from the side (i.e., external door, Wai Men), then your techniques will still be useless.</p>
			<p>If your opponent also uses the strategy of entering your external door, then you must use the internal door to attack (relative to him, you are still on his side door). Then you may still attack your opponent with the boring technique without opposition.</p>
			<blockquote>(If) using only one side of the palm (i.e., one palm attacks one side), the goal cannot be achieved. At least, it will need two sides (i.e., two palms from two sides) to attack. One sideways one forward will become triangle hands. This will make the opponent being controlled just like held in my chest (i.e., a certainty).</blockquote>
			<p>In Baguazhang, you should use both of your palms skillfully. If you are able to skillfully attack the opponent with only one of your hands, then you will not attack as successfully. Even if you do no: know how to attack your opponent from either the top or the bottom (i.e., kicking), at the very leas: you should know how to use both of your hands skillfully. In Baguazhang, both of your arms form a triangle, with one arm sideways in front of your chest and the other extended forward. When you do everything correctly and dexterously, then you are sure to control your opponent like an object held to your chest.</p>
			<blockquote>(When) high, desire to be low and (when) low, wish to raise. Diagonal body, circle stepping, do not hurry. Diagonal turning or reversed turning, the waist should conduct the power. When turning to the ultimate, the power must be hard.</blockquote>
			<p>This song is talking about the strategy of the body's movement. The first sentence can have two meanings. The first is that, when you are high you will change into low, and when you are low then you will raise into high. This helps prevent the opponent from figuring out your strategy. The second meaning is that, when the opponent is standing high or when he is tall, you will focus on a low attack. However, if he is low, then you will concentrate an attack higher up. such as his upper body or head.</p>
			<p>When you are walking the Bagua circle, the body twists to face the center. Your stepping should be firm and steady. Unless you have practiced for a long time, walking too fast will make your root shallow. When you are turning your palms, regardless of which turn you do, all of them must originate from and be directed by the waist, with a firm root. When all the turnings reach their final target, the Jin should become hard.</p>
			<blockquote>People say that the winning of the palm technique is decided by the hard (/in). The Fist Classic has also said that the soft (fin) should be hidden within. In martial arts society, someone has discovered its taste (i.e., essence or secret). The mutual assistance of the hard and the soft should be raised (i.e., emphasized, cultivated, or practiced).</blockquote>
			<p>This song is discussing the manifestation of Jin, which should be either hard or soft. Though there are many sayings about how the Jin should be manifested, in Baguazhang the soft and hard Jins should mutually assist and correspond to one another.</p>
			<blockquote>(If) the hard is first, then the soft should be hidden behind. (If) the soft is first, then the hard is manifested later. (To defeat) other people's soft, from the waist and the hands. (If) I am able to receive (my) waist (i.e., control and direct my waist) with steady stepping, then (I) will be winning.</blockquote>
			<p>This song continues the discussion of how to manifest Jin. If the hard Jin is being manifested, there must be some soft Jin hidden behind. This is necessary to prevent your opponent from using your hard Jin against you. When you are expressing hard Jin, the soft Jin is already prepared to deal with any sudden disadvantageous changes. If you use the soft Jin first, then after you neutralize and channel the opponent into a dis-advantageous position, you may use hard Jin to manifest your muscular power to its maximum. In theory, hard Jin is more appropriate for an attack and soft Jin is better used for yielding and neutralization.</p>
			<p>If your opponent is soft, and if he is not in an urgent situation, you should not use hard Jin. You must use your waist and hands skillfully to yield, lead, and neutralize his power. Only then will you have a firm stepping root, allowing you to win the battle.</p>
			<blockquote>When the application (of a technique) has reached its limit, the body must be turned. Escape the body, and change into shadow without leaving a trace. The key to change and variety is in the stepping. Exiting, entering, advancing, and retreating, the waist extends first.</blockquote>
			<p>This song is discussing the trick of the body's turning. When you are in an urgent position, you should turn your body to escape. When you escape, you are like a shadow and your opponent cannot figure out how you do it. The key to making this happen is in your stepping. All turning must begin with the waist, and the rest of the body follows.</p>
			<blockquote>The spirit of the turning palm (i.e., Baguazhang) is manifested from the neck bone. (When) turning and twisting the head, the hands should (move) first. When changing (the techniques), the head withdraws and when emitting, the head extends. (It) must be like a spiritual dragon connecting the head and the tail.</blockquote>
			<p>This song is talking about the spirit of Baguazhang. Baguazhang is also called "Turning palm." The spirit of Baguazhang is illustrated by the head, which is held as if suspended from above. The neck is upright and the spirit is raised. When you are turning your head to change direction, the hands should move first. When the r arrives, the Qi and the hands also arrive. When you are changing techniques, conserve your energy and store your Jin. During this time, your neck is withdrawn and relaxed. When you are emitting your Jin, the neck extends and the spirit is raised. The movement of the entire body, from the head to the limbs, is just like a swimming dragon.</p>
			<blockquote>When striking the opponent, the upper arms must be used as the root (of fin). The upper arms on the shoulder area should not extend completely. That means if (you) desire to advance, step forward with front leg. If (you) step forward with the rear leg, then the spiritual effort is in vain.</blockquote>
			<p>This song is talking about the tactics of attack. When you attack, the root of the strike is the upper arms, which are connected to the shoulder joint area. The shoulders should be sunk and not completely extended. Follow these rules and your striking power will be firm, rooted, and strong. In order to strike your opponent with power, you must utilize the momentum of the body's advancing movement. While doing this, you should step forward with the front leg instead of the rear leg. Stepping with the front leg makes you more firm and rooted while striking.</p>
			<blockquote>The abundant power (i.e., strong fin) is emitted from tendons and bones. The hard (fin) originates from bones and must coordinate with tendons. The big tendon on the heel is connected with the chest and spine (i.e., the entire body is united into one unit). When emitting techniques with following stepping, the power is able to smash.</blockquote>
			<p>This song describes the emitting of Jin. Physical power must be generated from the bones and tendons instead of the muscles. If the power is emitted from the muscles, it will be stagnant and slow. When the Qi stored in the bone marrow is manifested in the action of tendons, its power can be very fast and penetrating. Because the tendons of the feet are connected to the upper body, the entire body should act as one unit. If you are able to use the advancing forward stepping power, it can smash your opponent easily.</p>
			<blockquote>The eyes arrive, the hands arrive, and the waist and the legs arrive. The Xin (i.e., emotional mind) is real, the spirit is real, and the power is also real. The three "Reals" and the four "Arrives" combined into one place. There is a surplus to defend yourself, and (it) is able to defeat the opponent.</blockquote>
			<p>This song is talking about the mind, the spirit, and the action. In order to make your Qi abundant for fighting, you must first raise up your emotional mind (Xin). Yet this emotion must be under the control of your wisdom mind (K). In this way can your spirit of vitality be raised to a high and real level. When your Qi is abundant and your spirit is high, you will be able to energize the muscles and tendons to their maximum efficiency. When you are in a highly alert and agile condition, your eyes, hands, waist, and legs will move as one unit. If you have reached this stage in your Baguazhang training, you can not only defend yourself, but can also control your opponent.</p>
			<blockquote>The power should be hard, and even more, should also be soft. Too much of hard or soft, the power is hard to withdraw (i.e., control). (When it is) too hard, it is easy to break, (this is) the real object theory (i.e., natural theory). Too much of the elegant softness is equivalent to truce (i.e., useless).</blockquote>
			<p>This song is again talking about hard and soft Jins. Jin power should be hard as well as soft. If it is either too hard or too soft, it will be either too stagnant or too weak. In either case, the power is not alive and can be easily neutralized. When it is too hard, the power can be broken and borrowed, and when it is too soft, the power will not be strong enough to defeat an opponent.</p>
			<blockquote>What is the saying of the mutual supporting of the hard and the soft? It has never known difficulty if the hard and the soft mutually assist (each other). Hard and soft should use the Qian (i.e., Yang) and Kun (i.e., Yin) hands. This enables (one) to open the heaven, expose the earth, and cause the great wave in the ocean.</blockquote>
			<p>This is again talking about the hard and the soft Jins. Hard and soft Jins should mutually assist each other. When the hard and soft Jins combine with the Yin and Yang palms (i.e., insubstantial and substantial palms), its power can be very great and hard to defeat.</p>
			<blockquote>(When) the opponent is hard and I am soft, (this) is the right way. (However), if I am soft and the opponent is hard, the method is also good. The hard and the soft mutually coordinate and win (i.e., control) from the waist. The conflict (i.e., battle) is decided on whose stepping is better.</blockquote>
			<p>This song is talking about how to use the hard and the soft Jins skillfully. When the opponent is hard, you may use the soft Jin to yield, lead, and neutralize. In this case, your techniques will be varied and alive. However, if the opponent's power is soft and if the situation allows, the hard Jin can force the opponent into an defenseless situation. The most important factor in winning a battle is knowing the timing, and recognizing the right opportunity to apply the techniques. Only then can the power vary and exchange from hard to soft and from soft to hard according to the situation. In all of these situations, you must also know how to use the waist to direct the Jin, and how to use the stepping to create an advantageous situation.</p>
			<blockquote>When stepping, the waist is raised first. (If) retreating and withdrawing are appropriate, the marvelous (result) can be demonstrated. (If) the feet desire to move but the waist does not move, the stepping will be slow and unsteady and the opportunity will be delayed (i.e., lost).</blockquote>
			<p>This song is talking about how the waist can affect the stepping. Your center of gravity is normally located in the waist area. If you raise up your waist slightly when you step, you will be able to walk more agilely. When the waist is kept loose, you are more able to retreat or advance with correct timing. When you desire to step you must keep the waist area relaxed and steady. This helps to maintain your center and when you step, you will be steady and rooted. If you are not able to stabilize, center, and balance yourself while you are walking, you will be unable to appreciate opportunities for attack or execute techniques with correct timing.</p>
			<blockquote>(When) turning the body and changing the techniques, the stepping should not be long. Wiping the ground while walking; do not lose self-possession. Accurately look at the coming postures (i.e., attacks) then extend your hands. (Like) a cute girl threading a needle, be steady, soft, and hard (i.e., firm).</blockquote>
			<p>This song discusses movement. The stepping should always be coordinated with the body and the techniques. When you step, do not reach too far. Step in short distances; this can increase your stepping speed and stability. In Baguazhang, the stepping is as if you are walking on muddy ground. Baguazhang stepping is commonly called "Tang Ni Bu" (walking muddy steps).</p>
			<p>When you walk like this, your stepping will be firm. With coordinated stepping, and an understanding of the opponent's intention, the moment will come to attack. The entire action is just like threading a needle: accurate, firm, and steady.</p>
			<blockquote>(When) the opponent carries a sharp weapon, I am not busy (i.e., alarmed). The flying sword reaches my side from distance. Watch its coming and use the Hen and Ha (i.e., the sounds of emitting and neutralizing fins) to avoid. It is a good rule that evil cannot defeat the righteous.</blockquote>
			<p>This song is talking about the psychology of fighting barehanded against an armed opponent.  When you encounter such a situation, you should remain alert but do not panic. You must learn to trust your training, and be confident that you will coolly handle the situation under the principles of attack and defense. You must believe that evil will always be defeated by the righteous.</p>
			<blockquote>It seems hard to protect (yourself) when the short weapons are contacting (i.e., battle with short weapons). (I will) not be scared even (if the weapons are) as sharp as the Yu Chang sword. Extending (my) hands to seize it (i.e., to handle the situation) is just like picking up an object in a bag. Pointing (to) the mountain and striking the grind stone, the marvel is hidden within.</blockquote>
			<p>This song is talking about the strategy of fighting against an opponent with a short weapon. The Yu Chang (Fish Intestine) sword was a famous sword in Chinese history known for its sharpness. If I want to defeat the opponent who is using a sharp short weapon, the best way is by using faking techniques. The reference to the mountain and the grindstone is meant to symbolize a feint to one area, and an attack to another. In themselves, the mountain and the grind stone do not have any likeness or relationship. However, if you point your fingers to the mountain, your may draw your opponent's attention, distracting him while offering you a chance to attack the grindstone. In order to defeat an armed opponent, you must cheat him with both faking techniques and actual strikes.</p>
			<blockquote>The opponents are many, it is hard to fight against (them) with strength. Do not forget that the tricks (i.e., strategy) is able to break (i.e., defeat) a thousand pounds. One hand (i.e., a single person) cannot defeat (the opponent) depending solely on strength. Though the ox (is strong), yet it still fears the extension of the reverse bow.</blockquote>
			<p>This song talks about how to fight if there are many opponents. When you encounter this situation, you should avoid using force against force. You will not be able to compete with the combined forces of many opponents with your own force. You must instead use your wisdom and cunning. Often, wisdom is more powerful than a thousand pounds.</p>
			<p>In ancient China, a whip was commonly used to urge oxen and horses. Normally, the whip was also used as a bow. When the bow was unstrung, it became a whip (reverse bow). The ox is a very strong animal, yet it is still afraid of the whip. The reason that a human is able to control an ox is simply because our wisdom is higher than theirs. When you fight against many opponents at the same time, you should use your wisdom and fake the opponents, avoiding the strong and attacking the weak. Conserve your energy and use strategy to confuse your opponents.</p>
			<blockquote>(When) extending hands, (you) cannot see the opponent in front of (your) palms. Again, there is no oil lamp to illuminate the opponent's body. Withdraw the eyelids (i.e., relax) and strive to see. (Then, you can firm) the ground portion (i.e., of the body) and manifest your palms marvelously.</blockquote>
			<p>This song is talking about fighting in the dark. Since neither you nor your opponent can see each other, you should calm down your mind, relax your eyelids and search for any sign of movement. If you are tense and open your eyes too wide, then too much of your concentration will be focused on your eyes, and they will actually become a distraction. You should calmly, alertly and firmly pay attention to your surroundings. Only then will you move with a firm root, and the power of your palms can be demonstrated successfully.</p>
			<blockquote>Icy sky (i.e., cold weather), snowy ground (i.e., ground covered with snow), (again it is) raining, it is slippery. Do not hesitate to place the front foot sideways. When turning the body, must not spin like a screw. It is good if aware of these carefully either high or low.</blockquote>
			<p>This song illustrates what you should be aware of when you fight on slippery ground. When you step or are even standing still, your front foot should be turned slightly sideways. Doing this will enable you to move or stand with more stability. When you turn your body, do not spin or you will loose your foundation. You should turn slowly and carefully. Under such weather conditions, it does not matter if your posture is high or low, you must be very cautions.</p>
			<blockquote>When used (i.e., to fight), the most important (key) is the spirit of vitality. When spirit of vitality is brilliant and luminous (i.e., scintillating), the ears and the eyes are real (i.e., alert). (It) does not matter if the opponent's hands are (as fast as) a flying swallow, an ant's shouting to my listening is like a tiger's roaring.</blockquote>
			<p>This song is talking about fighting spirit. When your spirit of vitality is raised, you will be wholly alert to your situation. In this case, your ears and eyes will react fast and naturally. Even if your opponent's hands move as fast as a flying swallow, you will still be able to see them clearly. When you are in this highly alert condition, even the smallest sound or movement will seem as clear as a tiger's roar.</p>
		</article>
      </div>
    </div>
  </div>
</div>

<?php include "../../ssi/footer.php"; ?>

</body>

</html>