<!DOCTYPE html>

<?php
$globalNavId = "instructors";
$sectionNavId = "gates-of-heaven";
?>

<html lang="en">

<head>
<meta name="keywords" content="helen, dad, wushu, feel, water, day, people, life, medicine, time, family, doctor, style, qigong, lot" />
<meta name="description" content="Helen Liang?s Triumph over Tragedy, Battling Lymphoma with Qigong, Tai Chi and Chinese Medicine Helen's amazing story of her triumph over cancer was the cover story of the July/August 2003 edition of Kungfu/Qigong Magazine. We are happy to shar" />
<title>Helen Liang - Opening and Closing the Gates of Heaven - shouyuliang.com</title>
<?php include "ssi/meta.php"; ?>
</head>

<body>

<?php include "ssi/header.php"; ?>

<div id="syl-body-bkg">
	<div id="syl-body">
		<div id="syl-body1">
			<div class="contentWidth clearfix">
				<nav id="syl-breadcrumb" class="breadcrumbs pathway">
					<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/instructors/" class="pathway"> Instructors</a> <img src="/templates/syl/images/arrow.png" /> <a href="/instructors/helen-liang.php" class="pathway">President Helen Liang</a> <img src="templates/syl/images/arrow.png" alt=""  /> Helen Liang - Opening and Closing the Gates of Heaven
				</nav>

				<div id="syl-left-col">
					<?php include "ssi/menu_instructors.php"; ?>
				</div>

				<div id="syl-center-col">

<h2 class="contentheading">Helen Liang - Opening and Closing the Gates of Heaven	</h2>
<h2>Helen Liangs Triumph over Tragedy, Battling Lymphoma with Qigong, Tai Chi and Chinese Medicine</h2>
<br/>
<br/>
<p><img src="../images/instructors/helen_cover.jpg" id="magazineCover" alt="Helen Liang - Opening and Closing the Gates of Heaven" align="left" style="margin-right:15px;">Helen's amazing story of her triumph over cancer was the cover story of the July/August 2003 edition of Kungfu/Qigong Magazine.  We are happy to share the article here, and hope you may find your insights and hope in its story.  Many thanks to the folks at <A HREF="http://www.kungfumagazine.com/" TARGET="_new">www.kungfumagazine.com</A> for allowing us to present the article here!</p>
<br clear="all">
<br/>
<hr/>
<br/>
<p><b>By Martha Burr</b></p>
<p><img src="../images/instructors/helenliang/Helen_1.jpg" width="250" height="387" border="0" align="right" alt="Helen Liang - Triumph Over Cancer">Miracles are in short supply these days, though we seek them daily. Sometimes we find them, or possibly they find us. Seven years ago a beautiful young girl lay dying in a Vancouver hospital bed, victim of a rare and aggressive form of lymphoma. After a devastating course of chemotherapy failed to eradicate the disease, doctors told her that she had only two weeks to live. Her only hope was an extremely painful bone marrow transplant with a success rate of five per cent. Faced with death, many people would desperately cling to any offer of hope, but with courage rare in one so young, Helen Liang resolved to spend her final days out of the hospital, at home, trying to find a kind of peace with her family. Her father, the famous martial arts master Liang Shou-yu, refused to let her give up hope and embarked with her on a course of qigong, tai chi, meditation and alternative Chinese and Western medicine. Two weeks passed. She was still alive. Another two weeks, and then another. Week after week became five years. Whether to attribute the miracle to Kuan Yin, the goddess of mercy, to qigong, to bitter Chinese herbs, to a familys unwavering love, or Helens own will to heal her cancer, the answer is still a mystery. But seeing Helen today, performing her favorite martial art form, Liu He Ba Fa (Water Style), is poetry of the soul in motion, a miracle in action, and a dancing light beaming steadily out of the darkness that nearly extinguished her life nearly seven years ago.</p>
<p><b>Successive Rings of Fire</b><br />
It's not like Helen or her family had never known hardship. It was there from the beginning. She was born in a very remote village in China's Sichuan province in the middle of the Cultural Revolution, where her father had been forced to relocate after graduating from University for "re-education." Liang Shou-Yu was a famous wushu teacher, highly educated, and one of China's top coaches. Students of this poor Sichuan region were lucky. But luck hangs in the balance. As many people's fate spun out years later from that turbulent era, Helen's may have also been entwined with the politics that tore through wushu as through everything else. She says, "I was born in that village. I didn't even go to the hospital; somebody helped my mom with the delivery. In 1994 when my dad took a demonstration team back to China, he took me to that village to see the actual room I was born in. It was old and dark. People were poor then. I also have a younger sister, but my parents sent her to my grandparents in Chongqing city, because it was so poor and very difficult to take care of two children. They wanted the best for both of us. So in Chongqing she had a much better living standard, and that's why she's a lot healthier too. I was weaker because the facilities and the food. But they tried to provide me with the best they could."</p>
<p>Essentially Helen became the only child once her sister was gone, but, as she recalls of her early years, "Later on we moved to another town. I was with a whole bunch of other wushu sisters and brothers so it was never really like I was alone. That's when I started wushu, when I was about four years old, with my dad. He trained me every day. I remember how I would start a form each morning and I had to do it ten times. Every time you had to do it with a lot of power; my dad was very serious. You'd get really tired after three or four times, and you just don't want to do it, and he'd say, no  ten times. He'd come over and hug me and kiss me and then go  ok, keep on going! So I'd have to finish my form ten times every day."</p>
<p>Helen's youthful wushu training continued with her father until she was eight. Then he had the opportunity to go to Canada as a wushu coach. Seeing a better future for his family, he made the hard journey, leaving his family and students in 1980. He wouldn't be able to return for them until four years later.</p>
<p>Meanwhile, he told Helen she must keep on training. She had an extended wushu family to help her. "My dad left a lot of students," she says, "and he really had been a father figure to them, so they'd hang out at our place almost every day. My brothers and sisters -- and that's how I actually addressed them -- would come every day and train me, just like my dad would. Ten times every day. And of course I'd do the basics, as well. They would stay at my house, and my mom would cook for them. It was like a big family."</p>
<p>"Every day we would walk from my house to the training place, about forty minutes of walking. At that time there was no transportation, no car, you had to walk forty or fifty minutes to the place you train, and then walk back. But actually that was the fun part."</p.
<p>My dad would write back to us often, saying to my mom, 'Make sure Helen is training, and that she remembers her forms.' He put so much emphasis on it. I really missed my dad, but I was more mature. I would write to him, telling him don't worry about us, don't worry about Mom, I can take care of my mom. I would feel that my mom was lonely. And write to my dad that I was being a good girl, and not giving my mom trouble."</p>
<p>Life went on this way for several years. Helen trained, and wrote letters to him in Canada, which seemed very far away. When she was twelve she went away to the Sichuan Provincial Wushu school, and trained there for a year. Recalling her trip to the school, she notes, "I had to travel from that small town, and basically it's two days of boat ride. Then you get to Chongqing city, and then you had to take a train from Chongqing to Chengdu. At that time it was the capital of Sichuan. So I did all that on my own. People on the boat asked me, 'Where are you going?' I'd tell them, I'm going to the wushu school. 'Oh, wushu, do you know somebody named Liang Shou-yu?' I'd say yes I do, he's my dad. He's very well known in Sichuan province, especially around the Yangzte river. They'd say, 'Oh, you're in trouble. Your dad is in North America, and he's not going to come back, and he's not coming to get you guys.' At that time there are all these stories about how martial artists go to North America, and they get killed, fighting with people, stories like that! It was so frightening to hear. Or they'd say he'll find another wife and never return to you. So every time I'd hear that I'd say, no no, he's coming back, but I felt angry."</p>
<p>Helen trained at the Sichuan Wushu school for about a year, and then word came from her father that he was coming to take them to Canada. Finally the long wait, and her fears, were coming to an end. Still, even this happy event was touched by sadness as Helen's grandfather died just before the move. "My dad was very close to my grandfather," Helen says. "My grandfather practiced wushu too, and then he was a businessman who traveled to Hong Kong and Shanghai. He was very successful. But in his later years China didn't turn out to be the way he wanted it to be, because of a lot of things going on there, and it was quite sad. He always had high expectations for my dad. And my dad was coming back, after being established in North America, to take him out, but then he passed away."</p>
<p>Then it was time to move to Vancouver. "It was very overwhelming," Helen remembers, "My first time on an airplane. In my small town people hardly ever see any airplanes. Everything was very new to me. But I was young and easy to adapt to a different world."</p>
<p>At first Helen only studied English, in a class with students from many other countries. She recalls not being afraid, just trying to speak, and how her teacher liked her. Soon she went on into high school and became a normal Canadian school girl. Well, except for being one of the top wushu students in the country, still under the tutelage of her father who was now a professor teaching wushu at the University of British Columbia.</p>
<p>"I was still training quite a bit," says Helen. "I think in China going to the professional school was a good experience, but I do feel I got the most from my dad. My passion about wushu is from him. He influences you in a way that you love this art. He also emphasizes the culture, and the history of wushu, of China. He's concerned about your body's health, and doesn't push you, he's very careful, even with his students in China. He's taking care of you as a person. That's something very important. My dad would get us to read the Chinese martial arts novels, so that we don't forget Chinese, that's also important to him. We were so into those novels, every day. And that's partly how we kept up our Chinese language."</p>
<p>With her dad as her teacher Helen made dramatic improvements in her wushu. When she was seventeen she began teaching kids in her dad's school, and then later adults. "My life," she recalls, laughingly, "was really just school and wushu. And my parents were quite strict about us going out. So even though I was here in the West I guess I had a very different teenage life from other kids, who go out and hang out at parties and clubs. No, none of those for me. Just training, and then come home. A lot of its because theyre worried about us. So it was very strict. But they love us very much, and we're very close as a family."</p>
<p>Staying close to wushu and her family, Helen went to the University of British Columbia and studied Economics there. Her parents relaxed the rules a bit, but Helen still spent many hours in the library and hanging out with her friends. The year she graduated her father took a North American wushu team back to China to demonstrate and tour in 15 cities. It's the only time she's been back to China since her immigration.</p>
<p><img src="../images/instructors/helenliang/Helen_2.jpg" width="250" height="472" border="0" align="left" alt="Helen Liang - Triumph Over Cancer"><b>To the Edge of Darkness</b><br />
Upon graduation Helen got a job at a Vancouver bank. She was up for a promotion when all of a sudden she got sick. "It started with pulling wisdom teeth out and I got a bad infection. Even now they don't know what is the cause of lymphoma. I just remember I had a very high fever for nearly a month. I went to the hospital and they were trying to find out what it was; they thought it was some kind of infection. I stayed in the hospital for so long, getting different kinds of antibiotics. But nothing happened. Lumps started coming out, and it was very painful. It was awful. Once they were taking a biopsy, and I was there by myself early in the morning. Doctors came, and they took this huge needle, didn't give me any anesthetic, but drilled into me, and I fainted. My parents came while I was unconscious, for I don't know how long.'</p>
<p>The doctors did all kinds of tests. "One day my doctor came," Helen recalls, "he was also our family doctor and had always taken care of me. He referred us to this oncologist; I think he was already suspecting something. I remember one morning I was with my dad, just the two of us, and this doctor came in. 'I have something to tell you,' he said. 'I'm afraid Helen's got cancer.'"</p>
<p>"To me at that time, cancer was the end of the world. I was so young, and I'd been so healthy, and just graduated and had a whole life ahead of me, so I just felt I couldn't accept it. How could it be cancer? My dad was very quiet, he didn't say anything. The doctor continued, we have to treat her right away with chemotherapy. I didn't know what chemo was, I didn't have a clue. And then he left. "</p>
<p>"You always see it on TV movies, somebody gets cancer, and then they die, that sort of thing. And so right away, I was lying there, looking at my dad, he was holding my hand, and I was having so much pain at the time, and thinking cancerI just felt like crying, but I didn't cry. I didn't know what my feelings were. My dad said, 'Well you have to be strong.' I asked, what happens when I die? Where would I be going? Where are you guys going to be? And my dad said, 'Just make sure that if you see any kind of light'  hes into Buddhist and Taoist meditation  'if you see light you have to follow the light, you cant be afraid of it, you have to go there.' I was trying to imagine how that would be like."</p>
<p>"Then he had to go, he had a class that night. My mom came to stay with me. I was lying there that whole night and I didn't want to fall asleep because I was afraid in the darkness that I wasnt going to wake up again. Later on I heard that when my dad got to class -- he's very strong, never cries -- but later on students told me that he could barely talk, and he told me he was crying in the car by himself."</p>
<p>Helen started an aggressive chemo treatment, which was very difficult and harsh for her small size and frail body to take. "I had long hair," she says, "and of course they told me that Id lose my hair. Each new thing was something that you just can't imagine happening. One day in the shower a whole handful of hair suddenly came out. It took me so long but I couldn't get out of the shower. My dad was very worried, because I was very weak, and a lot of times I needed their help just to take a shower. I came out and I was crying. "</p>
<p>"My parents just felt so bad, and they tried not to show it in front of me. They gave me a lot of care, and my friends and their friends and a lot of doctors did too." Despite the debilitating effects of chemo, Helen also practiced qigong and meditation.</p>
<p>The chemotherapy went on for about 3 months, but after the final doses the cancer came back again a few days later. Helen started to get lumps once more, and developed a very high fever. "I was hospitalized again," says Helen. "They tried other things, but then they said to me, you only have a few weeks to live. The only thing we can do is try a bone marrow transplant. But the success rate of that is less than five percent. And we have to find the right marrow."</p>
<p>"Then they took me to a wing of the hospital and tried to show me what the transplant would be like. They showed me some of the people in there, and that was the most horrible thing that I remember. I saw all kinds of tubes running into their bodies, as I was passing by their rooms, and I just didn't feel it was a life any more."</p>
<p>The doctors told Helen they could not give her any other treatment for her cancer. This was the last hope they could offer. She had been in the hospital for three weeks with a raging fever, which no medicine was able to cure. "That afternoon," she says, "we had to make a decision on whether to go for a bone marrow transplant or not. I remember that day. All my family was there for this decision, because it was an urgent issue. And nobody could make that decision. I had to make the decision. So eventually I was thinking about the pros and cons. I think my Dad was leaning towards not doing it and seeking alternative medicine, but he couldnt really make the decision for me. I was just sitting there and I was thinking, Ive looked at those people and is that a life that I really want? And the chances were less than five percent. Do I want my last few days to be in that room, or do I want to be with people I love and do the things I wanted to do? It was a hard decision."</p>
<p>"But finally I said, I'm just going to enjoy the next few weeks. And do whatever that I have to do. But my aunt reminded me, now Im already experiencing so much pain, later on it will get worse and worse. It will be very painful. But I said that's OK, at least I'm home, Im with you guys. Its OK."</p>
<p>Helen went home, tended by her entire family and her family doctor. He practiced Western medicine but he had also learned qigong with Liang Shou-yu as well. This doctor supported Helen leaving the hospital and Helens parents when they said they wanted to search for an alternative medicine treatment. Her father, says Helen, would do anything.</p>
<p>After seeing her life drain away in the hospital, Helen was at least glad to be home. She recalls, "After I made the decision I went down to the beach and all of a sudden it's as if I have thrown away all the burden. I feel it's OK. Im just going to do what I have to do for the last few weeks, and every day I'm not going to give up. My dad's still telling me to do meditation, do qigong. And it so happened that day that theres a doctor, a close friend of my dad's, in Seattle. He called and said, 'I know this Chinese doctor from Beijing, maybe he can help.' My dad said, yes, lets try."</p>
<p>After contacting this Dr. Wang, Helen described her illness and symptoms to him over the phone. He wrote a prescription and faxed it immediately. "We went to get these Chinese herbs," says Helen. "My parents were forcing me, saying you have to take this, at least just to kill the fever for now. You have to just try. Of course the bowls of this bitter Chinese medicineI was so weak, and Id take just a little bit and I would throw up. But I forced myself. I'm not giving up, I thought, and I'll do whatever I need to do. So I took the medicine for a few days, and my fever did start to get better. I had diarrhea but that's how the medicine works, how the medicine gets rid of the impurities in your body, so that's supposed to help you. So at least my fever was more in control.</p>
<p>"I was more relaxed, and I was doing qigong and tai chi with my dad every day. We'd go out doing all kinds of qigong because it's good for you to stay outside and get a lot of oxygen. Thats supposed to kill the cancer cells. So we're outside two-thirds of the day, my dad and friends and everybody taking turns, taking me out, walking on the beach. We had to stay away from the crowds because my immune system was really low, very weak. So I just took Chinese medicine, doing qigong and tai chi."</p>
<p>Helen did this routine for one week. Then another. Soon it was three weeks. "I say oh, three weeks, I'm still around. And I know everybody is feeling that way, they just dont want to say it. They don't want to get excited. They're very careful. And my dad is very strict, saying you have to go out every day, get as much oxygen as possible. And do qigong and a lot of meditation. And take the medicine. Then we combined it with another medicine, from another alternative medicine doctor, a Western doctor. Some kind of medicine that's supposed to boost your immune system. I was giving injections to myself. That was a very painful process, because I had to stay in bed for an hour or two just doing the injection to my stomach area. All the medicine, from China, from different places, it cost my parents a lot of money. Every month thousands and thousands of dollars."</p>
<p>Slowly, Helen's body began to heal. For the next six months Helen's cancer would come back a little bit, but then go away. The combination was working. Little by little her strength came back to her, and by the end of one year she was finally regaining her body and spirit.</p>
<p><img src="../images/instructors/helenliang/Guanyinti.jpg" width="200" height="317" border="0" align="right" alt="Guan Yin - Helen Liang's Triumph Over Cancer"><b>Healing Light -- Buddhist and Taoist Qigong</b><br />
As Helen's recovery progressed she practiced Buddhist and Taoist qigong with her father, and also a serious amount of meditation by herself. "Every day," she recalls, "I'd go in the backyard where we had flowers and bamboo. In the morning, facing the sun, with no noise, I'd sit and meditate. Id combine methods, and shorten them, tailor them to me. I focused sometimes on the goddess Kuan Yin; I'd feel peaceful whenever I'd think of her. So Id do something that has something to do with her, visualize an image of healing light.</p>
<p>"Another thing that really helped me, I found it myself. I would sit there and imagine I am one with the universe, almost that Im not there. When you think about that, how immense the universe is  the good, the bad, disease and everything, how everything moves on, recycling, coming in a circle  you're no longer afraid of anything. I'd think, I'm not even sick right now, I'm the universe  feel how powerful the universe is  I'm not there and yet Im powerful."</p>
<p>"Sometimes feeling pain, the side effects from chemo, I'd feel horrible, that's when I meditated the most. I'd wake up and feel refreshed  feel peaceful and powerful  I was the universe."</p>
<p>As her body healed Helen had the strength to practice more taiji and other internal styles, particularly her favorite Liu He Ba Fa (Water Style). In the quiet bamboo shade of her garden, or the salty air of the Vancouver beach, Helen's focus never wavered. She took in life moment by moment, day by day, becoming one with nature.</p>
<p>"Everyone tried not to talk about it at the beginning," she remembers. "Then three weeks passed, four weeks passed, then I just dont think about it anymore. One of the things I learned the most is let nature run its own course. Don't worry about the outcome. Worry about the process, and let nature go from there. Always try your best, but don't worry. If you fail and lose, it doesnt matter. That's part of nature."</p>
<p>"At the beginning when the doctor told me there was nothing they could do, and I only had a couple of weeks, I was in denial. I asked why? I never knew the answer. I couldn't pull myself out. And with this disbelief, I was scared and depressed."</p>
<p>"Then, I found some kind of answer. It depends on how you look at this thing and what you learn from it. Now, I can say I dont feel bad what I went through. I wouldnt say I'd want to re-live it, but the experience, and what I learned, it was a very special experience. I dont feel bad because I learned so much. There were enlightenments that I really, really treasure. I can feel it, I know it."</p>
<p>Many people have trouble with meditation because they dont know how they are supposed to feel, and have a difficult time disengaging from the mundane thoughts of everyday life. Few people achieve the kind of deep focus that was afforded Helen by being on the edge of the abyss, but the very fact that her meditation was a life or death matter may have produced an exceptional human experience.</p>
<p>"During meditation," she says, "if you could reach a stage where you're in a state of bliss, you don't feel yourself. Its hard for anybody to reach that kind of state. It is the ultimate state. A few times I reached that. That kind of happiness cannot be described. Its blissful. But only two or three times I had that kind of experience. I have not felt it recently. Meditation now, I do it in a different way. But then, my mind wasnt thinking about anything else  just healing yourself everyday. Every second, every minute, healing yourself."</p>
<p>Helen recalls reading the martial art novels her father gave her as a teenager, and says she felt like one of those mystical Taoist hermits. Forced to stay away from people and crowds due to her low immune system, she found her real peace with herself and nature, in the backyard garden, in the park, on the beach. "It was a quiet and peaceful feeling," she says, "which I carry with myself from that time onward."</p>
<p><img src="../images/instructors/helenliang/Helen_3.jpg" width="250" height="442" border="0" align="left" alt="Helen Liang - Triumph Over Cancer"><b>For All the World to See</b><br />
After a profound year of meditation, qigong, and internal martial arts Helens hair had grown back. Still frail, the experience only seemed to make her beauty all the more ethereal. It was then 1997, and promoter Jeff Bolt was having a groundbreaking event in Orlando, a pay-per-view sanshou fight coupled with a live demonstration performance featuring the top wushu talent of North America. It would be the first broadcast of its kind, and was much anticipated by the entire American martial arts community.</p>
<p>Liang Shou-yu was one of the top stars, and Helen was invited to perform as well. She had not performed in a long time. Her body was still weak, and she was tentative about performing the Water Style form in its entirety. Again, it was her father who pushed her forward, nurturing her, encouraging her. She found the will and the strength and the courage to get on the stage, and by the end of the night she was the star of the show (though she will deny this with her characteristic modesty, I was there helping to coordinate the show, and can vouch for the star quality coupled with a spiritual serenity which made her beloved by both the audience and her peers).</p>
<p>Helen's healing remained on strict schedule. "My mom brought 3 jars of Chinese herbal medicine to Orlando. My hair had grown back a little by then. Orlando was a good experience for me. It was the first time after I got sick that I actually did the whole Liu He Ba Fa. I tried my best to do that. It was very tiring but it was good."</p>
<p>The Orlando event was an important milestone in her recovery, giving a much needed psychological and emotional boost to Helen, for not only was the physical wasting of lymphoma devastating to her body, but the mental trauma was also something difficult to conquer. Returning to the hospital that had both failed and given up on her was a hard road to retrace. "For a long period of time," she says, "I was afraid of going back to the hospital. I had very bad feelings as soon as Id go in. My dad knows that. Hed say, go in, take it lightly, it doesnt matter if it's the hospital, park, or here. Make sure you have that peace inside you, no matter where you are."</p>
<p>Her experience with the oncologist, from the beginning, had gone from bad to worse. He was not only final in his pronouncement that Helen's illness was terminal, but he also openly scorned alternative medicine. "He told me nothing could be done. He couldn't accept the fact we did alternative medicine, and called my doctor bad names. After chemo and fever for so many weeks my body was all bones, I couldn't move, I was lying in bed. He saw where I was giving myself injections, and was furious that Id gone to that other doctor. Later on that oncologist also did terrible things to my family doctor, and tried to bring him to court."</p>
<p>"But my family doctor stayed by my side, and the Chinese doctor too. I refused to go back to the oncologist. Since I left the hospital Ive had no contact with him. Half a year later he called me once. My impression was that he called to see if I was still around! I heard later he was in disbelief. I never called him back. And refused to go back to the hospital to have him check me."</p>
<p>They say if you can last the first five years after cancer your survival rate is good. Even as the clock ticked away, Helen didnt count time quantitatively, but qualitatively, living each moment, each day to its fullest. She has never gone back to be checked for the lymphoma. "I dont think I ever got a confirmation," she says. "If I feel good, I feel good. I don't want to hear them say anything. Let it be. If I feel sick, I'll go to a doctor. I just want to feel normal. Of course this is a very special situation, and rarely anyone has one like it. My type of lymphoma was an extremely aggressive one. A rare type."</p>
<p>A careful regimen of continued meditation, qigong and martial arts practice continues to keep Helen healthy, though her immune system remains delicate and vulnerable. She still gets sick more than most people, and has to be careful about her health. But most of all, she realizes you can't take anything for granted. "My illness was an amazing growing up experience, even though I suffered so much growing up at that age. I had these youthful dreams and then it hits you  all of a sudden the world stops for so many years."</p>
<p>"After all, you come to realize how much people care. I owe my parents so much. They love us so much. I couldn't believe how much energy they put in, and love. Also, I was fortunate to have friends and my parents' friends who were very good to me and there to care for me. So to me, I always treasure friendship, and material stuff is not important. I dont talk about what they have done, but I always remember. I keep it inside me."</p>
<p><img src="../images/instructors/helenliang/waterBoxing_video.jpg" width="242" height="293" border="0" align="left" alt="Helen Liang - Video Cover - Water Style Boxing"><b>Wushu, Water Style and the Way</b><br />
Today, seven years later, Helen still practices wushu every day, and teaches at her father's school in Vancouver. "Wushu remains an inseparable part of my life," she says. "I've been doing it since I was a little child. When I needed it so much it helped me. Before I loved it as an art, a very complete art. If you love something you find it always completes your life. When youre younger external styles seem more exciting, and they're beautiful, they have strength, require stamina, they train your will. I still love that, but now I do more internal martial arts. When I'm in an internal mode, I can find myself more. Whenever I do this form ( Liu He Ba Fa  Six Unities/Eight Principles  also known as Water Boxing or Water Style,) I'm totally with it. It's that meditation kind of feeling. Plus the theories and histories of Water Style, and my evolving understanding of it, has brought me to an even higher level."</p>
<p>Since her public performance of Liu He Ba Fa half a dozen years ago Helen has become one of its best-known masters. When Kungfu magazine first published her article on it in 1997, following her Orlando performance, dozens of letters poured in and the demand eventually produced Helen's instructional Water Boxing video. According to Helen's article, Liu He Ba Fa is believed to date back to the 10th century, created by a Taoist hermit in Huashan to benefit ones health, strengthen the body, get rid of sickness and attain longevity. It is no wonder that she became a master of it.</p>
<p>"My love is Water Style, I feel it's my true expression," she says. "Naturally, I always like to associate Water Style with that element's characteristics, and I'm very fond of water. People say Helen, you look gentle, but you have strength and power. Later on I came to realize, yes, I am like that  and even if I'm not, I'd like to be. As it says in the Tao Te Ching,</p>
<blockquote>Under heaven nothing is more soft and yielding than water. Yet for attacking the solid and strong, nothing is better; it has no equal. (verse 78)</blockquote>
<p>"I love that passage. Water yields and receives. It has no edge, no shapes, no limits. It can absorb, and erode firmness. It can absorb and be powerful. This idea ties in so much to my life philosophy, and Water Style itself. Water can appear very gentle and beautiful, but so powerful, have so much strength and be so receptive."</p>
<p>"The Tao Te Ching also discusses that to have is to not have, not to have is to have. That kind of paradox  I feel very linked to that. To be simple, really, if you can find the peace. Always bringing your peace with you. Simplicity. Harmony. Everything I talked about, eventually it's going towards harmony. With yourself, people around you, harmony with nature. I strive very hard for that. The ideas are so deep, and I feel Im at the very beginning here. I feel it will take me a lifetime, to always learn from this.</p>
<p>I liken many things nowadays to Water style. There's speed in the form and slow parts. It's so much like human life. Sometimes you work, work, work and then you need to rest. Conserve your energy. Use it and apply it when its the right time. When you dont need it, dont use it. That's how I see life as well."</p>
<p><img src="../images/instructors/helenliang/Helen_4.jpg" width="250" height="527" border="0" align="right" alt="Helen Liang - Wushu - Emei Snake Style"><b>Looking Ahead</b><br />
Outwardly there remains no sign of the ravaging illness that nearly extinguished Helen Liang's life. Her delicate beauty is deepened by the experience in her eyes, and by a calm that emanates from her person. And yet, between moments of calm and reflection internal energy also fuels a power you can see in her martial arts and her quiet passion for living.</p>
<p>"More and more I try to find something that is beneficial from the simplest thing, an everyday occurrence that's happening around me. I try to take that experience with me, make it something I can learn from. Innately that ability was always there, but I never had a chance to bring it out, to contemplate it fully. My experience with illness really magnified it. Now it's up to me to explore."</p>
<p>Today Helen is a financial consultant at the bank, and continues to teach wushu at her father's school. "I think martial arts would always be an inseparable part of my life," she says. "Of course there's a lot more I need to explore and learn in martial arts. I want my children to learn martial arts. There are a lot of expectations for my family. Family is important to me. Family in harmony is important. Id like to train, teach, and ever influence my children in the future. And students too. I'd really like to have my skill in martial art, and my experience, influence people in a positive way."</p>
<p>Helen teaches wushu forms and taiji, but not Water Style yet, though her video has introduced the form to many practitioners. But she hopes to use Water Style as an instrument that can contribute to contemporary culture and bring a profound understanding to more people.</p>
<p>"I think that this very ancient thing can link to modern society," she says, "and have a place in the modern world. Water Style combines theory and practice with a person. By understanding, and practicing Water Style, learning how that builds up strength  it may enable people to even reach enlightenment."</p>
<p>And when asked about being a female role model doing this powerful and complex form, Helen smiles her characteristic humble smile, but remarks, "I think a girl doing Water Style can really bring a lot of positive things."</p>
<p><b>Acceptance</b><br />
Both the Buddhism and the Taoism that inspire the qigong that helped to vanquish Helens illness place an emphasis on balance. Balance between acceptance and empowerment, between human will and the Tao of the universe.</p>
<p>"If I have a piece of advice," she says, "it would be to learn acceptance. If you have an illness, accept the fact that you are sick. I was in denial, but when I made the decision not to go for bone marrow I accepted the reality. Accept it as something normal, not sad or tragic. This is happening to me  what can I do? Accept different things, different people. Tolerance is very important. Become more adaptable. That way you never lose your center.</p>
<p>"Events happen in life  one links to another, fate, chance. Everything happens for a reason. I can't say exactly what the reason is. But because of the things that happened to me I think Im in a much deeper state now. Otherwise, it would take me another 30 years to realize. So I feel grateful. It puts things in so much more perspective."</p>

				</div>
			</div>
		</div>
	</div>
</div>

<?php include "ssi/footer.php"; ?>

</body>

</html>