<!DOCTYPE html>

<?php
$globalNavId = "instructors";
$sectionNavId = "journey-from-sichuan";
?>

<html lang="en">

<head>
<meta name="keywords" content="liang, wushu, students, training, shou, martial, teacher, friends, china, day, red, time, ability, town, people" />
  <meta name="description" content="By Master Wen-Ching Wu Grandmaster Shou-Yu Liang was featured on the cover of the October 2000 issue of Kungfu/Qigong Magazine. The magazine published an excellent in depth biographical article on him by Master Wen-Ching Wu, Master Liang's prot?g" />
  <title>Shou-Yu Liang - Journey from Sichuan - shouyuliang.com</title>
<?php include "ssi/meta.php"; ?>
</head>

<body>

<?php include "ssi/header.php"; ?>

<div id="syl-body-bkg">
	<div id="syl-body">
		<div id="syl-body1">
			<div class="contentWidth clearfix">
				<nav id="syl-breadcrumb" class="breadcrumbs pathway">
					<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/instructors/" class="pathway"> Instructors</a> <img src="/templates/syl/images/arrow.png" /> <a href="/instructors/shou-yu-liang.php" class="pathway">Founder - Grandmaster Shou-Yu Liang</a> <img src="templates/syl/images/arrow.png" alt=""  /> Shou-Yu Liang - Journey from Sichuan
				</nav>

				<div id="syl-left-col">
					<?php include "ssi/menu_instructors.php"; ?>
				</div>

				<div id="syl-center-col">

<h2 class="contentheading">Shou-Yu Liang - Journey from Sichuan</h2>

<b>By Master Wen-Ching Wu</b>

<br>
<br>
<p><img src="../images/instructors/syl/art1a.jpg" width="111" height="150" border="0" style="border:solid 1px #000; margin-right:15px;" alt="Shou-Yu Liang - Journey from Sichuan" align="left" style="margin-right:15px;">Grandmaster Shou-Yu Liang was featured on the cover of the October 2000 issue of Kungfu/Qigong Magazine. The magazine published an excellent in depth biographical article on him by Master Wen-Ching Wu, Master Liang's prot&eacute;g&eacute;. We are happy to reprint the article on Grandmaster Liang's extraordinary life so that everyone can learn and know about this unique teacher. Many thanks to the folks at <A HREF="http://www.kungfumagazine.com/" TARGET="_new">www.kungfumagazine.com</A> for allowing us to present the article here!</p>
<br clear="all">
<br />
<hr/>

<br />
<img src="../images/instructors/syl/art1b.jpg" width="400" height="417" border="0" alt="Shou-Yu Liang - Journey from Sichuan" align="right" style="margin-left:15px;">
<p>When speaking of Grandmaster Liang, Shou-Yu, there are few people in Chinese martial arts that have not have heard of him.  Besides his obvious talents and what has already been written about his Kungfu abilities, there is a lot more to his story than most people could ever imagine.  Grandmaster Liang's life is filled with bittersweet memories, yet he still has great aspiration and enthusiasm, and continues to strive for self actualization while helping other to reach their full potential.</p>
<h3>The Beginning</h3>
<p>It was about 5 a.m.  Laoyeye took his ceremonial bell and rang a few times, a signal for his 6-year-old grandson to wake up and begin his morning training.  The young boy was still tired and sore from the training the night before.  His eyes had a hard time opening.  The young boy struggled with his tired body and got up to meet the bitter challenges.</p>
<p>Laoyeye is Liang's grandfather, Liang, Zhi-Xiang, an expert in Wushu and Dapeng Qigong. Laoyeye was the most influential person in building Liang's Wushu and Qigong foundation. His martial arts skill and Iron Shirt was so amazing that it nearly cost him his life! Once, while Laoyeye was walking on a narrow city street in Chongqing, he was so busy thinking about the day's business meetings that he failed to move aside for the eight man carriage rushing from behind. The carriage belonged to the local high military official. They owned the streets! When they would come, people had to give way, squeezing themselves tightly against the walls to avoid carriage. The eight man carriage, without a pause, ran into Laoyeye with full force. Laoyeye instinctively rooted himself. The Iron Shirt he developed from his Dapeng Qigong training kept him safe and grounded. The carriage, on the other hand, was bounced backwards several feet. Laoyeye turned around, realized what had happened, and took off from the spot quickly before he could be identified. If he were caught, he would be severely punished or hung, for what happened would surely be considered a serious offense at that time.</p>
<p><IMG SRC="../images/instructors/syl/art1d.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="right" style="margin-left:15px;"> Starting at age 6, the young Shouy-Yu's day began with two hours of Dapeng Qigong and foundation training. The training began on the dantian (a pressure point below the navel) and gradually extended to the baihui (a pressure point on the top of the head) and the rest of the body. When training the grueling Iron Shirt components of Dapeng igong, his body often turned red and discolored. No normal child could enjoy the training. Being an obedient child, and with great respect for Laoyeye, he persevered.</p>
<p>For 10 years, not a day went by without training Dapeng Qigong under the tutelage of his grandfather.  Even during holidays, the training continued.  Shou-Yu's mother often complained to Shou-Yu's father, requesting that he speak to Laoyeye to ease off on her young son.  But Shou-Yu's busy father was very much in favor of Laoyeye's strict training of Shou-Yu.  Shou-Yu's father was very busy running the family business, and therefore his grandfather took on the majority of responsibility for training him.  His father would have trained Shou-Yu himself if he had the time, after running the day to day affairs of the family business.  He was also trained by the grandfather.  This was a family tradition.</p>
<p>In the beginning, the neighbors also complained about the loud noises from hitting and conditioning of young Shou-Yu's body.  Laoyeye ignored them and kept up with Shou-Yu's training.  As time went by, the neighbors got used to the noise.  It had become like clockwork; when the noise started, they knew it must be daybreak.</p>
<p><IMG SRC="../images/instructors/syl/art1c.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="right" style="margin-left:15px;"> Young Shou-Yu began to appreciate the training more and more when he realized that he was a lot stronger than his friends and could withstand strikes without getting hurt.  Once, during second grade, his school had a special performance and celebration.  The teacher knew that Shou-Yu trained Kung Fu, so they asked him to perform for the audience and demonstrate applications on a teacher.  The teacher attempted to punch to his head, so young Shou-Yu dropped down into ma-bu (horse stance), intercepted the punch up with his left arm and punched towards the teacher's abdomen with his right fist.  The teacher screamed so loud that it made the audience jump back.</p>
<p>Shou-Yu was well-liked in school. Later, teachers and classmates would joke with him about hitting the teacher. Young, innocent Shou-Yu was truly astonished that the teacher could not even take a punch and had screamed so loudly. He would offer his abdomen for his teachers and classmates to hit. Many would take him up on his offer, but no one was able to make him let out any sound of pain. Years later, many of Liang's friends still joke about his occasion whenever they meet.</p>
<p>When Liang graduated from high school, not everyone was able to go to college and not everyone had a choice to major in the field they wanted.  For his exceptional school record and test scores, at age 17, he entered the Southwest National University with a full scholarship to study biology.  He was an honor student studying science, but Wushu and athletic sports was what he desired to study.  After completing his course work, he would walk over to the nearby Chengdu Athletic University to train Wushu and other sports.  Even though he was not officially enrolled at Chengdu Athletic University, he was there every afternoon to train with the regular students.  His ability, his desire to learn, his character, and his hard work were warmly received by the instructors and professors.  They encouraged and welcomed him to train unofficially.</p>
<p><IMG SRC="../images/instructors/syl/art1e.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">The professors were very touched by his dedication and often praised him in front of other students, &#168;Look, Liang Shou-Yu is not an athletic department student, but he trains harder than you!&#168; Jokingly and sarcastically, his classmates would say to him, &#168;Today, the teachers are praising you again... you must be possessed by Wushu.&#168;</p>
<p>Finally, he became the Wushu coach for the Southwestern National College and a member of the Chengdu City Wushu Team. His love of Wushu also drove him to test his skills at wushu schools in the area in order to further his sanshou, Taijiquan, and push hands abilities.<IMG SRC="../images/instructors/syl/art1f.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="right" style="margin-left:15px;margin-top:10px;"> Whenever he found someone that was good at some Wushu style or Qigong, he would exchange teaching with them. While in college he researched and studied Mizong and other Qigong. He competed in many Wushu and sanshou competitions and received numerous gold medals. Most athletes competed in internal or external styles only. Liang often competed in both, plus shuaijiao and sanshou; and often he received the all around title.</p>
<h3>The Young School Teacher</h3>
<p><IMG SRC="../images/instructors/syl/art1g.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">Liang was a college graduate, his father was a businessman, and his uncle was in the U.S., so he had ties overseas.  All of this classified him as having a bad family beginning during the political situation of the time.  So he was assigned to teach grade school in a very remote farming village after graduating from college.  The villagers were very poor.  The children had no shoes to wear.  The clothes they wore had patches on patches.</p>
<p>Liang lived and ate with the villagers in a small hut. He helped them with farming during planting and harvesting season, and taught school during the school year. He gave them his own clothes, blankets, shoes, and taught the children Wushu. The children were hard working people. Today, many of them have become Wushu instructors in different branches of the military and police academies.</p>
<p>Liang never ceased to train on his own.  He would help the villagers with many other chores including grinding the wheat into flour.  He would work the two person stone grinder by himself, using this opportunity to strengthen his rooting, body movement, and connection to his arms.  To go to the nearest town for a meeting, he had to walk over 90 kilometers.  He would use this opportunity to train his legs by jogging to the meeting.  For that, he was nicknamed the &#168;little legs that could fly.&#168;</p>
<IMG SRC="../images/instructors/syl/art1h.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">
<h3>The Wandering Years</h3>
<p>Within two years after beginning his assignment at the remote village, the disastrous Cultural Revolution started. Even though he had outstanding reviews for his work and had a wonderful relationship with the local people, he could not escape the criticism and impending humiliation and persecution by the Red Guards...</p>
<p>To protect himself, his friends, and family, Liang trained a protective team at his home town of Chongqing City and at the remote village where he taught.  When the Red Guards attempted to persecute him, he also had to fight for his life. <IMG SRC="../images/instructors/syl/art1i.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;"> Even though all his belongings were ransacked by the Red Guards, he was fortunate and was never captured by them.</p>
<p>Liang and his Home Town Defensive Team and their ability spread from the local level to the region. Red Guard leaders sent the &#168;Martial Striking Unit&#168; to arrest him. Liang realized that it was time to leave. His friends and students escorted him and two other schoolteachers several kilometers out of the village. When they saw that there was no one following them, they parted ways. What they didn't realize was that dozens of Red Guards were waiting just beyond the turn of the road, ready to ambush them.</p>
<p>With only the clothes he had on, a handful of food, and an umbrella, Liang bade farewell to his friends and students.  Just as he made the turn, the Red Guards jumped out of the bushes, swinging their fists, sticks and knives at him.  Knowing the cruel treatment he would receive if he were captured, he was not about to become the next victim.  He reacted swiftly.  Blocking to the right, striking with the tip of the umbrella to the left, kicking to the front, then turned and dropped the person that tried to grab him from behind.  Within a few seconds, there were several attackers on the ground, slow in getting up.  The remaining attackers hesitated, looking at Liang with anger and fear.  Seeing the attackers' hesitation, Liang signaled to the other two schoolteachers and took off quickly, without realizing what was in store for him.</p>
<p><IMG SRC="../images/instructors/syl/art1j.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">The next town in his journey was only a day's walk away. Liang had many friends in that town, and it was logical for him to seek shelter and food there. Looking forward to seeing his old friends and having a roof over his head, and some food in his stomach, he and the two schoolteachers walked in that direction. Just as they were about a kilometer from the town, Liang realized that he had another good friend a few kilometers to the north of this town. He had not seen this old friend in a long time. Since he didn't have any specific destination on his journey, he decided to go see this old friend. The two schoolteachers continued to the town. It was fortunate that Liang himself did not continue there that day.</p>
<p>After visiting his friend in the north, a few days later he continued on his journey and walked into town.  As he did so, a friend recognized him, and immediately pulled him aside and told him to stay out of sight because the Red Guards were looking for him.  His friend told him that a few days ago the Red Guard's Martial Striking Unit was waiting with machine guns to arrest him - for resisting arrest and for attempted murder a few days before.</p>
<p>The Red Guards he had injured had to stay in the hospital for serious internal injuries.  They also radioed ahead to the towns surrounding the incident.  <IMG SRC="../images/instructors/syl/art1k.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;margin-top:10px;">Other Red Guards did arrest the two schoolteachers and someone that had a physical resemblance to him.  They tied that man up and beat him senselessly until he was unconscious.  After many pleas and affidavits from the local people that the man they tortured was not Liang, the Red Guards realized their mistake and released him without an apology.  The search continued for Liang and a more severe torture was in store for him.  Realizing the consequences of being captured, Liang left the town quickly avoiding serious torture and possible death.</p>
<p>During the years of the Cultural Revolution, Liang went from city to city, province to province, and mountain to mountain, in search of more knowledge and abilities. He met many new martial arts friends, studied with more grandmasters, and learned even more about Wushu. Liang was in his early twenties, but still looked like a teenager. That was a blessing. As he traveled from place to place, he was able to blend in with the local Red Guard groups. Doing so, he was welcome to share the communal meals and had a place to stay everywhere he went. But there were scary times. He had to cautiously pretend to belong to the right wing group when he was in their territory. When he encountered the left wing group, he pretended to be part of their group. It was lucky for him that he never stayed in one place too long. If either group recognized him as being part of the other, he would have been severely punished.</p>
<table cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td valign="top">
		<IMG SRC="../images/instructors/syl/art1l.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">
		<h3 style="clear:none">The Start of Professional Wushu Coaching</h3>
		<p>Towards the end of the Cultural Revolution, Liang returned to the remote village to continue his duties.  Order was being reestablished.  Wushu also was gradually being revitalized and his Wushu ability was quickly recognized by the regional leaders.  He was reassigned as the professional Wushu coach by the Sichuan Department of Physical Education.  In the beginning, no sanshou or shuaijiao competitions were allowed, and all Wushu coaches needed to learn the new performance routines.  He was not an exception, so he began learning the new routines at once.</p>
		At the time, there were two types of Wushu coaches.  One type was the professional coach that was responsible for training performers and teams for performances.  The other was the coach that was responsible for managing and developing Wushu in the city or region.  Liang was the latter.  He took his job seriously, and worked hard in the managing, promoting, and training of students.  He also never stopped training himself.  One of the best training times for him was during competitions.  During the day, he would lead his well-organized team in proper uniform, in unison in and out of the competition.  His team consistently was top ranking.
		</td>
	</tr>
	<tr>
		<td>
		<IMG SRC="../images/instructors/syl/art1m.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">At night, like a loving father, he would make sure all his students were covered up with blankets and resting comfortably.
		<p>During the week-long competitions at night he would take the opportunity to meet his old friends and make new ones to exchange techniques.  In fact, the next competition started when the registered competitors had finished their day.  When the competitors had left it was the judges and the coach's turn to have unofficial competitions!  Whenever Liang took his team to compete, he would hardly sleep.  After spending time coaching his students, he wanted as much time as he could in improving himself.  He would sleep no more than an hour a day during the week to ten-day long nationals.</p>
		</td>
	</tr>
</table>
<p><IMG SRC="../images/instructors/syl/art1n.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="right" style="margin-left:15px;">As it was from ancient China, without real Kung Fu ability, one would never be able to solidify one's footing as a martial arts coach. The only way one could prove their ability and gain acceptance was in defeating challengers. Professional coaches, especially those that were not originally from the region, were always challenged by other martial arts experts. Liang's position was challenged numerous times. When the older generation master would visit him, he would treat them with respect and ask for their guidance in the promotion of Wushu. These older generation masters were all very supportive of Liang's work. Liang accepted all the challenges by martial artists of the same generation. He had never lost a match. In fact, from the challenges he met many long lasting friends, and solidified his coaching position; but they also caused him several reprimands for seriously injuring the challengers.</p>
<p>Once, a Kung Fu expert well-known in the region came to challenge him.  This man could break a walnut with a simple flick of his fingers, and could split a piece of rock in half with a simple pecking of the finger.  Liang knew his challenger's strength and avoided his fingers with his Emei Xiaoyao steps, while counterattacking with shuaijiao techniques.  The challenger was dropped several times.  After that challenge, they also became good friends, and the challenger would tell others about Liang's ability everywhere he went.</p>
<p>Although Liang tried not to injure his challengers, sometimes it was unavoidable.  Once a challenger came towards him with full force.  Liang was never one to underestimate an attacker's ability.  This time he overestimated the attacker's ability.  As they engaged, Liang used his Dapeng Iron Shirt to deflect the oncoming challenger.  The challenger was bounced across the room, and had to be rushed to the hospital for internal injuries.  Feeling regrets for using too much force and causing such a bad injury to his challenger, Liang went to the hospital the following day to wish him well.  The challenger was so touched that tears flowed out of his eyes as he held onto Liang's hand with both his own.</p>
<p>Liang produced many outstanding martial artists.  His promotion of Wushu was also having popular results.  In 1978, he was recognized as the Outstanding Coach of Sichuan Province.  The following year, in 1979, Liang was nominated and recognized in the national recognition of outstanding coaches in China.  He was given one of the 17 Coaches of Excellence award titles.  In those years, he was often assigned to judge in national Wushu competitions, and on other occasions he was selected to represent Sichuan Province in the national Wushu Exhibitions.  His enthusiasm and physical ability was so amazing that at age 38 he once again competed in the Sichuan Traditional Wushu Competition and won the All-Around Grand Champion title.  In that competition he was the oldest competitor!</p>
<p>In fact, up until his early 40's he was still jumping and spinning around like people half his age.  He taught and practiced sanshou and high difficulty performance routines with his students.  Movements like a butterfly with a twist, tornado kick landing on the kicking leg, no handed cartwheel, front flip, and back flip were simple moves.  In shuaijiao training, he would practice with one student after the next until all the students were tired before resting.</p>
<h3>The Sentimental Journey</h3>
<p>Liang had an aunt and uncle that lived in Seattle. He hadn't seen them since the Chinese civil war. They were also his godparents. They missed him and wanted their nephew to visit them in the U.S. At the time, China had just reopened its doors to the West. The relationship with the U.S. was improving steadily. Liang was one of the earlier people that was granted permission to leave China and come to the States.</p>
<p>In 1981, Liang came to Seattle, a journey which would mark another major turning point in his life.  Liang was excited about going overseas to visit his godparents.  But leaving his parents, wife, two young daughters, friends, and home was an emotional experience.  As he was boarding the ferry at the Chongqing port to leave his home town, thousands of friends and students came to see him off, wishing him a safe journey and to request that he return soon.  Police officers rushed to the site, thinking that some type of emergency had happened.</p>
<p>The overwhelming outpouring of emotion on that day almost stopped him from leaving.  With a smile on his face, and tears rushing down his cheeks, he wanted to speak, but words got stuck in his throat.  At every stop along the Yangzi River, more friends and students came to say good bye and remind to return quickly.</p>
<IMG SRC="../images/instructors/syl/art1o.jpg" ALT="Shou-Yu Liang - Journey from Sichuan" ALIGN="left" style="margin-right:15px;">
<h3>Teaching as an Exchange of Energy</h3>
<p>Liang is a great teacher with a great attitude, a man who lives his life with virtues and without pretense.  He uses the martial arts virtue as a guide for himself and his students.  He never uses it as a method of control.  He believes all human beings are equal.  No one person is better than the next.  An individual may be more evolved, more knowledgeable, have a higher IQ, be physically stronger, etc.; but it does not make the individual more superior than the other.  It is simply the state from which people are to learn in this life.</p>
<p>In fact, the Chinese term for the teacher and disciple relationship stresses that point.  The teacher addresses the student humbly as tudi, meaning disciple younger brother.  It is like guiding a younger brother!  The disciple, however, will address the teacher respectfully as Shifu, meaning teacher father.</p>
<p>Grandmaster Liang often uses the statements, &#168;We will cultivate together,&#168; &#168;We will mutually learn from each other,&#168; and &#168;We will mutually help each other.&#168;  He has so much to offer, yet he is also willing to listen and learn from others.  When he shows mutual respect for the student, it is not an elevation of the student's status.  It is a humbling experience for the student.  When a teacher with decades more experience than the student is humble, how can a student with less experience be arrogant?</p>
<h3>Return Visits to China</h3>
<p>Liang quickly established himself as one of the best in the field. Within a few years after arriving in North America, Liang had settled in Canada and had a team ready to show what he had been able to accomplish there. He led a team of Wushu athletes to compete in the First International Wushu Invitational held in Xian, China. The Canadian team took third place overall. The following year Liang again led the Canadian team to the Second International Wushu Invitational held in Tianjin, China. With the 26 nations that competed in Tianjin, Canada took second place overall, with the host country, China taking first.</p>
<p>The Canadians' amazing success surprised China.  The story was reported in many newspapers, on radio stations and TV stations, of course, they especially emphasized the fact that Liang was from Sichuan, and still radiates the aroma of the Emei Mountain fragrance.</p>
<h3>Establishing the International Wushu Sanshou Dao Association</h3>
<p>Liang had always been a traditional martial artist at heart. He likes the physically challenging maneuvers in some of the contemporary Wushu routines, yet he also adored the sanshou component of Wushu. Seeing that Wushu was gradually becoming separated into performing and sanshou components, he wanted to start and organization that nurtured students with both the artistic performing ability and the sanshou fighting ability. He believes that a well-rounded martial artist must be able to do both, not just one or the other.</p>
<p>In 1989, he got together with many of his good friends and students from China, the U.S., and Canada, and founded the International Wushu Sanshou Dao Association (IWSD).  The headquarters is currently in Vancouver, Canada and the Administration Office is currently in Rhode Island, U.S.A.  Liang was selected and remains the Chairperson.</p>
<h3>Today...</h3>
<p>Since the beginning of the 1960's, Grandmaster Liang has personally taught over 10,000 students.  Additionally, he has touched the lives of tens of thousands of students in his affiliate schools and schools of students' students.  His students have received hundreds of gold medals in national and international competitions.  Many are currently teaching all over the world.</p>
<p>Grandmaster Liang continues to gain recognition in China and abroad.  In the past few years, Liang was selected as &#168;The Instructor of the Year&#168; by <I>Inside Kung Fu</I> Magazine, and selected by the <I>China Wushu Magazine</I> in the &#168;Biography of Today's Extraordinary Martial Artists.&#168;  He has been awarded the &#168;World's Top 100 Outstanding Martial Art Professional Award.&#168;  He has also been selected to be included in the &#168;Current List of Famous Martial Artists&#168; and in the Chinese &#168;Who's Who in the World.&#168;  The chairman of the China Wushu Association wrote about him that Liang,&#168;uses his martial arts to teach people, and uses his morals to inspire people.&#168;</p>
<p>Currently Grandmaster Liang is the Advisor or Honorary Advisor of over 20 national and professional Wushu organizations in China, the United States, and Canada.  He has written and produced several books and video tapes including: Hsing Yi Chuan, simplified Tai chi Chuan with Applications, Baguazhang, Qigong Empowerment, Chinese Fast Wrestling for Fighting, and Xiaoyaoshuai.</p>
<p>As he approaches sixty, Liang Shou-Yu is still a generous and forgiving teacher, but his feisty nature has subsided much.  His focus is now on his family, friends, and students; and continuing the promotion of Wushu.  As he was fortunate enough to learn from his teachers, he is now focusing his knowledge onto his students, and writing books to preserve what he was privileged to have learned.</p>
<hr width="40" size="2" noshade style="color:#aaaaaa;">
<p class="small"><B>Master Wen-Ching Wu is Grandmaster Liang's prot&eacute;g&eacute;. He has co-authored several books with Grandmaster Liang, including Qigong Empowerment, and Xiaoyaoshuai. They are currently embarking on a kung fu book and an advanced qigong book to be released in the year 2000. He currently teaches at The Way of the Dragon School in Rhode Island by night, and he busily writes at The Way of the Dragon Publishing by day.</B></p>

				</div>
			</div>
		</div>
	</div>
</div>

<?php include "ssi/footer.php"; ?>

</body>

</html>