<!DOCTYPE html>

<?php
$globalNavId = "classes";
$sectionNavId = "taiji-13-postures";
?>

<html lang="en">

<head>
<meta name="keywords" content="thirteen, taijiquan, postures, taiji, body, jin, steps, means, techniques, kao, skills, peng, opponent, wubu, style" />
<meta name="description" content="It is said that all of the taijiquan skills originate from variations and combinations of the Taiji Thirteen Postures. However Taiji Thirteen Postures does not refer merely to thirteen different postures or movements, it is the essence of taijiquan" />
<title>Taiji 13 Postures - shouyuliang.com</title>
<?php include "ssi/meta.php"; ?>
</head>

<body>

<?php include "ssi/header.php"; ?>

<div id="syl-body-bkg">
	<div id="syl-body">
		<div id="syl-body1">
			<div class="contentWidth clearfix">
				<nav id="syl-breadcrumb" class="breadcrumbs pathway">
					<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/classes/index.php" class="pathway">Classes</a> <img src="/templates/syl/images/arrow.png" /> <a href="/classes/taiji-class.php" class="pathway">Taiji</a> <img src="templates/syl/images/arrow.png" alt=""  /> Article - Taiji 13 Postures</span>
				</nav>

				<div id="syl-left-col">
					<?php include "ssi/menu_classes.php"; ?>
				</div>

				<div id="syl-center-col">

<h2 class="contentheading">Taiji 13 Postures</h2>
<p><img src="../images/taiji13-article/taiji1.jpg" style="width:267px;height:400px;float:left;margin:0 15px 5px 0;background:#eeeeee;">It is said that all of the taijiquan skills originate from variations and combinations of the Taiji Thirteen Postures.  However Taiji Thirteen Postures does not refer merely to thirteen different postures or movements, it is the essence of taijiquan, the key that unlocks the secret of all taijiquan. It refers to thirteen basic skills that are the foundation of all taijiquan skills.</p>
<p>Taiji Thirteen Postures is also commonly known as <i>bamen wubu</i>. <i>Bamen</i> translates as "Eight Doors" or "Eight Gates." <i>Wubu</i> means "Five Steps." <i>Bamen</i> is the theory of bagua (Eight Trigrams) in taijiquan	It refers to the eight positions of bagua.  Both taiji and bagua are Taoist philosophical theories.	They are cosmological perspectives that provide a framwork for many Chinese, traditions such as traditional medicine, fortune telling and feng shui. The martial arts of taiji and bagua are based upon this theory too. <i>Bamen</i> consists of four straight directions, called <i>sizheng</i>, and four diagonal directions or four corners, called <i>siyu</i>. <i>Si</i> means four. <i>Zheng</i> means upright, straight, correct, main, chief and positive. <i>Yu</i> means corner or diagonal. According to <i>Taijiquan Treatise</i> by Zhang Sanfeng (believed to have created taijiquan in the Song Dynasty), the four straight directions are <i>peng</i> (ward-off), <i>lu</i> (roll-back), <i>ji</i> (press or squeeze) and <i>an</i> (press or push). In Eight Trigrams theory, these four straight directions correspond to four of the trigrams: <i>qian</i> (heaven), <i>kun</i> (earth), <i>kan</i> (water) and <i>li</i> (fire) respectively. The four diagonal directions are <i>cai</i> (pluck), <i>lie</i> (split), <i>zhou</i> (elbow-strike) and <i>kao</i> (body-strike or bump). They correspond to the trigrams of <i>xun</i> (wind), <i>zhen</i> (thunder), <i>dui</i> (lake) and <i>gen</i> (mountain). Furthermore, <i>peng, lu, ji, an, cai, lie, zhou</i> and <i>kao</i> are referred to as <i>bafa</i> (Eight Methods), as they represent eight different kinds of fighting techniques. These eight fighting techniques equate to eight kinds of <i>jin</I> (power manifestation) patterns that correspond the eight positions of bagua.</p>
<p><i>Wubu</i> refers to the five skills revolving around footwork. <i>Wu</i> means five. <i>Bu</i> means step. The Five Steps corresponds to <i>wuxing</i> (five elements). In reference to Zhang Sanfeng's <i>Taijiquan Treatise</i>, the five steps are <i>qianjin</i> (advancing), <i>houtui</i> (retreating), <i>zuogu</i> (look to the left), <i>youpan</i> (glance the right) and <i>zhongding</i> (central settling). The words "look" and "glance" in "look to the left" and "glance he right" are merely metaphors used to describe leftward and righnward actions with footwork and body movements. In five elements theory, they correspond to <i>jin</i> (metal), <i>mu</i> (wood), <i>shui</i> (water), <i>huo</i> (fire) and <i>tu</i> (earth) respectively. These five footwork skills train the body to move in the most flexible way during fighting.</p>
<p><img src="../images/taiji13-article/taiji2.jpg" style="width:300px;height:200px;float:right;margin:0 0 5px 15px;background:#eeeeee;"><i>Bamen</i> and <i>wubu</i> combine together to form the Taiji Thirteen Postures. These thirteen postures are the main essence and fundamental structures of taijiquan. Every traditional style of taiiiquan contains thirteen postures and they are considered to be the source of all styIistic variations of taijiquan. Each style of taijiquan has its unique training method with the thirteen postures. When these thirteen postures are well coordinated, taiiiquan sequences can be performed gracefully like that of the floating clouds and the flowing water. This, in turn, will allow a vivid display of the body movements with a balance of the soft and the hard, the substantial and insubstantial. Only when eight techniques and five steps are combined in unison, can Taiji Pushing hands and free sparring applications be carried out in most fluid manner and the body's, <i>jin</i> be fully utilized. The harmonious interaction of these thirteen fundamental skills has resulted in the emergence of (hundreds and thousands of application techniques, inducing such notable "using the soft to defeat the hard", "lead the coming force into emptiness" and "use four ounces to neutralize one thousand pounds." To help practitioners better understand coordination between the eight techniques and five steps let's take a look at a few examples.</p>
<p><i>Peng</i> - Ward Off</p>
<p><img src="../images/taiji13-article/taiji3.jpg" style="width:267px;height:400px;float:left;margin:0 15px 5px 0;background:#eeeeee;"><i>Peng</i> has outwardly expanding kind of <i>jin</i> pattern. It is not only limited to the arcing of two arms, but extends to the entire body including the two legs, chest and the lower and upper back. All of these body parts, should be able to carry out <i>peng jin</i>. To execute this <i>jin, zhongding</i> from the <i>wubu</i> is of paramount importance. <i>Zhonyding</i> allows you to be as still and solid as a mountain so that your opponent - be it one person or numerous people - will be incapable of uprooting you. Many taiji masters are able to use only one arm to ward off numerous people at once with the application of <i>peng jin</i> My father, Grandmaster Shou-Yu Liang, used to randomly pick ten or more people from an audience at his demonstrations to push against both of his arms. He would use <i>peng jin</i> to ward off hese people. He has demonstrated this technique many times in the past. These demonstrations even led to a special interview by the Discovery Channel. The key to effective application of this technique is combination of <i>peng jin</i>, executed mainly by the two arms, and <i>zhongding</i>, which allows a steady and firm center and root in the stepping action. The lack of either one of these two components will allow your opponent to defeat you.</p>
<p><i>Lu</i> - Roll Back</p>
<p><i>Lu</i> involves using the hands to roll back and neutralize the coming force or make your opponent lose balance. However, when applying the technique of <i>lu,</i>	it is not enough to use only the <i>jin</i> of your arms and waist, as this may only work on beginners. To make it fully effective, the coordination, of footwork is required. When you are applying <i>lu</i> on left side, your left leg must step back <i>(houtui)</i> and your body must turn slightly to the left <i>(zuogu)</i>. With a right-hand-side <i>lu</i> your right leg needs to step back while your body turns co the right <i>(youpan)</i>.</p>
<p><i>Ji</i> and <i>An</i> - Squeeze and Push</p>
<p><i>Ji</i> is a forward and sometimes sideward kind of <i>jin</i> pattern that requires both hands or arms to press or squeeze forward sideways.  <i>An</i> is often used for forward and downward attack. In order to effectively use <i>ji</i> and <i>an</i> to defeat your opponent, <i>qianjin</i> should be used at the same time. You should advance forward and enter into your opponent's center of gravity to be able to uproot your opponent's foundation.</p>
<p><img src="../images/taiji13-article/taiji4.jpg" style="width:300px;height:200px;float:right;margin:0 0 5px 15px;background:#eeeeee;"><i>Cai</i> and <i>Lie</i> - Pluck and Split</p>
<p><i>Cai</i> means to pluck downward. <i>Lie</i> means to split. A splitting action will need two forces executed in opposite directions.  To defeat your opponente using these two techniques you must take bigger backward steps <i>(houtui)</i> with the turning of your body in either <i>zuogu</i> or <i>youpan</i>.</p>
<p><i>Zhou</i> and <i>Kao</i> - Elbow Strike and Bump</p>
<p><i>Zhou</i> refers to the use of elbow for forward, sideways or backward attacking. This kind of attack can be coordinated with all five steps. <i>Kao</i> means to use part of your own body to strike or bump the opponent's body.  <i>Kaojin</i> can be divided into back <i>kao</i>, shoulder <i>kao</i>, hip <i>kao</i>, chest <i>kao</i> and others.  <i>Kao</i> may be accompanied by forward, backward, and sideways footwork.</p>
<p><img src="../images/taiji13-article/taiji5.jpg" style="width:267px;height:400px;float:right;margin:0 0 5px 15px;background:#eeeeee;clear:right;">These simple and straightforward examples show but a few of the various combinations of <i>bamen</i> and <i>wubu</i> The application of techniques in taijiquan embodies countless variations.  Very often, when using the eight basic techniques, we do	not employ them one at a time; rather, we combine several techniques.  This is also true when using the five steps; we do not rely on only one step, but use a mix of several steps or even all of the five steps.  Even when using all five steps, there will be times when we fail to gain the winning ground. This is because our opponent is also a master of <i>bamen</i> and <i>wubu</i>. During these times victory depends on many factors, such as the timing of a certain technique, the proper lead into a certain direction, the difference in our level of martial skills and many other factors.</p>
<p>As a proficient taijiquan practitioner, one must understand he concept and the usage of the thirteen fundamental postures and remain open and flexible to the countless variations of these thirteen skills. One also needs to practice, since practice makes perfect. The Chinese have a saying: "Body movements become natural when practicing the fist forms one thousand times, sacred rules and principles emerge when practicing the fist forms ten thousand times." This clearly states the regimen for our everyday training.</p>
<p>My father Grandmaster Shou-yu Liang has been practicing Chinese martial arts since 1948 and has accumulated  encyclopaedic experience and understanding from learning, practicing, teaching, lecturing and writing. Taijiquan is one of the many styles that Grandmaster Liang has mastery over.  He started his Taijiquan training in the 1950s. He first started practicing Yang style, then started the training of Chen style in the early 1960s and later went on to learn Sun style and Wu style taiiiquan. He was a taiji champion in Sichuan province for three consecutive years in the 1970s and represented Sichuan when participating in the national martial arts exhibition.  Utilizing his more than fifty years of teaching experience, Grandmaster Shou-Yu Liang created two Taiji Thirteen Postures forms - the Simplified Taiji Thirteen Postures and Yin Yang Taiji Thirteen Postures. These two forms display the thirteen postures in a very clear manner that practitioners at all levels should find easy to comprehend.</p>
<p>The simplified Taiii Thirteen Postures routine primarily aims at providing an easier framework for beginner taijiquan practitioners to better understand the basics of Taiji Thirteen Postures.  Yin Yang Taiji Thirteen structures its movements in such a fashion that every movement is done on both left and right side, and each movement has yin/yang and soft/hard counterparts. Movements embody both explicit and hidden <i>jin</i> as well as soft and explosive <i>jin</i>. The martial application for each side of the movement has its own uniqueness. To make it more diverse, this routine also includes some of the typical movements from Yang, Chen, Sun and Wu style taijiquan.</p>
<p>These two Thirteen Postures forms are perfect guides for practitioners to better understand the essence of all taijiquan styles.	 Not only are they aesthetically appealing when performed, every movement is highly practical in its application. With their versatility, the two forms can be practiced for health, fitness, performance or application purposes. These forms have become overwhelmingly popular in the short few years since their introduction to the genenal public. May these form bring practitioners much health and wisdom!</p>
<p>Master Helen Liang is the eldest daughter of Grandmaster Shou-Yu Liang and the President of the Shou-Yu Liang Wushu Taiji Qigong Institute in Vancouver, Canada.</p>
<p align="center"><img src="../images/taiji13-article/taiji6.jpg" style="width:800px;height:534px;margin:15px;background:#eeeeee;"></p>
				</div>
			</div>
		</div>
	</div>
</div>

<?php include "ssi/footer.php"; ?>

</body>

</html>