<!DOCTYPE html>

<?php
$globalNavId = "newsletters";
?>

<html lang="en">

<head>
<meta name="keywords" content="Daoist Qigong, Daoist Religion, Philosophy, Grandmaster Shou-Yu Liang, Master Wen-Ching Wu" />
<meta name="description" content="Daoist Qigong - Daoist Religion and Philosophy, By Grandmaster Shou-Yu Liang and Master Wen-Ching Wu" />
<title>Daoist Qigong - Daoist Religion and Philosophy - shouyuliang.com</title>
<?php include "../../ssi/meta.php"; ?>
</head>

<body>

<?php include "../../ssi/header.php"; ?>

<div id="syl-body-bkg">
  <div id="syl-body">
    <div id="syl-body1">
      <div class="contentWidth clearfix">
        <nav id="syl-breadcrumb" class="breadcrumbs pathway">
          	<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/newsletters/" class="pathway">Articles</a> <img src="/templates/syl/images/arrow.png" /> <a href="index.php" class="pathway">2005 July/August</a> <img src="../../templates/syl/images/arrow.png" /> Daoist Qigong - Daoist Religion and Philosophy
        </nav>
		<article>
	        <h1 class="contentheading">Daoist Qigong - Daoist Religion and Philosophy</h1>
	        <h2>By Grandmaster Shou-Yu Liang and Master Wen-Ching Wu</h2>
	        <br><br>
			<p>During the Later Han Dynasty (947-950 A.D.), Zhang Dao-Ling founded Five Unit of Rice Dao, the first religious organization that used the Daodejing as the theoretical foundation for their beliefs. The name, Five Unit of Rice Dao, was derived from the requirement set forth for becoming a member of this organization. Each member was required to contribute five dou (a unit of grain equals about 10 pints) of rice. Followers of Zhang Dao-Ling referred to Zhang as the Heavenly Teacher. Therefore, this early Daoist religious organization was also known as the Dao of Heavenly Teachings. This Daoist group used the Daodejing as their main study text, and they regarded Laozi as their symbolic leader. When the term daoyiao (meaning use Dao to teach) also became the popular term referring to the Daoist religion, other schools of thought in China gradually stopped using this term to refer to their teachings.</p>
			<h3>Daoist Philosophy</h3>
			<p>Daoists believe that the Dao is the </i>Origin</i>, the </i>Source of the Great Cosmos</i>. Dao is that which is beyond what our languages can explain and beyond what our mind can comprehend. Dao is a conceptual term for the principle governing all that we know and don't know, and all that we can see and can't see. Dao has no shape and can't be fully felt with our limited senses. Dao is unobjective, yet encompasses all. Dao is within and beyond space and time.</p>
			<p>Dao should not be opposed. Opposition will only result in disaster. In the describing the Dao, terms such as Void, Emptiness, and Undefinable are often used. Dao is unlimited. The term Dao, itself, is reluctantly used as a reference to satisfy the human need to classify people and things into different categories. Since Dao is the origin, the root of everything in the Great Cosmos, it can't be fully explained with the language we know. Because when it is explained as 'A' it is differentiated from 'B'; when it is explained as 'B', then it differentiated from 'A'. We need to use our heart and spirit to feel and experience its essence, to know what it is.</p>
			<p>When Dao is limited by our perceptions and classifications, then it can't be the origin of the Great Cosmos. If our mind were to concretely figure out what Dao is, then Dao will have lost its totality. This is like the mind bogging example of, going half the distance each time, from point A to point B. One can never get to point B, if one only intellectualizes and uses human created rules to reach their destination. Dao, however, will continuously reveal many insights accompanied by unfolding realizations for its seekers.</p>
			<p>To use our limited language to set a definition for the Dao would only lead to erroneous conclusions. Dao is beyond the limitation of linear time and three dimensional space. It therefore can't be proven by conscious thinking, with everyday language, and man made scientific reasoning. That was why the first verse in the Daodejing states that, "Dao that can be explained is not the complete Dao". To realize Dao one needs to understand from proper cultivation and experience.</p>
			<p>The Dao has been explained with the term Void, implying that which transcends duality and the comprehension of the ordinary, limited mind. It is Undfinable. Void in this case does not mean nothingness. It simply implies that which was in the beginning. Daoist philosophy begins from the view that the Great Cosmos is an integrated whole. They believe that the Dao of the Great Cosmos and the Dao of life all comprise the same patterns and principles of nature.</p>
			<p>The profound nature of the Dao gives its seekers different insights as they think, approach, and continue with their own unique stages of realization. Philosophers use Dao, government uses Dao, military forces use Dao, martial artists use Dao, and astrologers use Dao. Everyone uses Dao. Dao encompasses all and is unlimited. The famous Chinese poet, Su Dong-Po (1036-1101 A.D.) wrote this about Dao:</p>
			<blockquote>"A man born into this earth blind, has never seen the sun. He asked people what the sun looked like. One person told him that the sun is shaped like a gong. One day he heard the sound of a gong and he thought that it was the sound of the sun. Another told him, the light from the sun is like the light from a candle. He then touched a candle stick to know its shape. Later he touched a short section of a flute and he though it was the sun".</blockquote>
			<p>Su Dong-Po's poem reminds his readers that all things are part of the Dao, but not the complete Dao.</p>
			<p>Referring to the Dao, Laozi had this to say, "Great scholars work unceasingly when they hear of the Dao. Mediocre scholar are bewildered when they hear of the Dao. Ordinary scholar burst into laughter when they hear of the Dao.</p>
			<p>Here Dao refers to the universal </i>Truth</i>. It is everywhere. Whether or not an individual is able to comprehend the Dao depends on one's current experience and understanding. Great scholars realized how little they knew compared to the greatness of the Dao. They cultivated unceasingly to experience it. When the mediocre scholars heard of the Dao, they were uncertain and couldn't decide whether to believe the Dao, or not, due to their insufficient experience and knowledge. They however, knew enough not to dismiss it totally. When the ordinary scholars heard of the Dao, they burst into laughter and thought of it as nonsense. They laughed because of their lack of experience and understanding. It is because they laughed that showed the extensive nature of the Dao. If they had not laughed, it would not have shown the profoundness of the Dao.</p>
			<p>The Daodejing contains the foundation and the outline of Daoist philosophy. Even though its content is broad and extensive, it can be boiled down to two words <b>Dao</b> and <b>De</b> (Virtue). To take it one step further, it can be boiled down to just the word Dao. When one has attained complete realization, all the ritualistic formalities are discarded. Everything becomes simple and clear. Because everything in the cosmos is of the Dao, and Dao encompasses all things. When one has attained the Dao, one will have mastered the true nature of all things.</p>
			<p>The characteristics of Dao are natural, complete, basic, untainted, simple, uncontrived, flexible, yielding, not contending, etc. When expressed in human action it is called De (Virtue). Therefore the book by Laozi is referred to as the Daodejing. The highest form of Virtue is natural and invisible. It is from within, silent, and expressed without mental processing. Whatever the characteristics of the Dao are, will also be the characteristics of Virtue.</p>
			<p>We have not fully realized and attained the Dao, therefore, we must speak of Virtue and its cultivation. The continual cultivation of Virtue assists us in realizing and attaining the Dao. When we have achieved Dao, it is no longer necessary to speak of Virtue, because everything will already be in unity with the Dao. Without Virtue, one will not be able to realize and attain the Dao.</p>
			<p>It is imperative that one understand the meaning of Virtue, the relationship between the Dao and Virtue, as well as the relationship between Virtue and cultivation. If one doesn't understand Virtue, doesn't value Virtue, doesn't cultivate Virtue, and doesn't maintain the integrity of Virtue, one will only remain in a state of qi, and be unable to continue the evolution of the spirit to attain the union of the spirit and the Dao.</p>
			<p>The inherent nature of Virtue is true goodness, with a heart that is filled with loyalty, filial piety, kindness, compassion, equality, universal love, passion to enlighten others, honesty, consideration, graciousness, patience, courage, forgiveness, etc. "One must not speak, if it is disrespectful; not listen, if it is disrespectful; not look, if it is disrespectful; and not act, if it is disrespectful." When Virtue is complete, the heart will be calm. With a calm and pure heart, Dao will be attainable.</p>
			<p>Virtue is often categorized as Genuine Virtue, Mystical Virtue, Yin Virtue, and Apparent Virtue. Genuine Virtue is natural and uncontrived, without any formulated mental process. It is a genuine and natural expression of the harmony of Dao and De.</p>
			<p>Mystical Virtue is the expression of Virtue by cultivators in the process of nurturing the spirit. They are knowingly and unknowingly helping others and society by healing the sick, helping people in trouble, protecting the balance of nature, etc. They are able to do good deeds without people knowing.</p>
			<p>Yin Virtue must rely on the physical body to express. Do kind deeds without expecting rewards. Do kind deeds without leaving names. Even though Yin Virtue is not completely in accordance with nature, it is the foundation of a true cultivator. It is important to continuously work on Yin Virtue to cross over to Mystical Virtue.</p>
			<p>Apparent Virtue is one that is visible to others, and rewarded with material and/or verbal gratitude. Apparent Virtue is an even exchange of energy, there is no accumulation of Virtue for the cultivator. People that only donate money and do kind deeds when they can gain prestige and fame don't accumulate Virtue. If one does good deeds and expects to be rewarded, it is no longer a Virtue.</p>
			<p>The cultivation of Virtue is not without rewards. Its "reward is in the heavens" and in the Dao. It is reward without shape or form. It is important to note that the high level of achievement in one's qigong cultivation is not totally dependent on practicing qigong, it is also dependent on the cultivation of Virtue.</p>
			<p>With each kind deed, one's heart becomes purer and the activities of the spirit increases. The gap between the subjective thinking and the spirit will be reduced. People that cultivate Virtue and the Dao will develop a strong presence that attracts help from everywhere.</p>
			<p>Almost all the religions in the world today, along with researchers of spiritual phenomenon, hypnotists, etc., all value the importance of accumulating Virtue. They use prayers to request for help and protection, and repent to purify one's spirit. Prayers and repentance can assist in one's cultivation. In Daoism, before one engages in high level training, one must also pray, communicate and pledge to one's teacher that they repent for all the wrong they have done and promise to engage in accumulating Virtue.</p>
			<p>Chapter 33 of the Daodejing effectively summarized the Daoist philosophy of nourishing life and attaining the Dao. This Chapter emphasized self-awareness, self-control, contentment, and aspiration:</p>
			<blockquote>"Knowing others can only be considered being intelligent; knowing one's own character is to attain true clarity of being." This verse states, to understand others we need to have the ability to distinguish different behaviors. To distinguish behaviors we need to be intelligent. To understand ourselves, we need to gain the ability to reflect internally. To reflect internally, we need to regulate our emotions, restrain our desires, control ourselves, and be generous.</blockquote>
			<p>We can see far into the distance, yet we can't see our own eyebrows. We can see the small errors of others, yet we can't see our own faults. The more time we spend criticizing others, the more we lose, because we have less time to reflect internally. The more time spent learning about ourselves, the more we can cultivate our character and attain higher realization. Ancient Chinese compare intelligence to a candle, and clarity of being to a mirror. As a candle burns, it become shorter; on the other hand, as a mirror is being polished, it becomes clearer. That is why Laozi did not value intelligence and holds clarity of being in high esteem.</p>
			<p><b>"Winning over others is strong; winning over oneself is true power."</b> We all have different degrees of selfishness and different degrees of lust. It does not matter how strong we are compared to others, we can't use this strength to conquer our own selfishness and lust. The only way to remove our selfishness and lust, is through introspection and removing our undesirable traits. Because this is difficult to do, people that are able to remove undesirable traits are considered to have true power.</p>
			<p><b>"Being content is being wealthy."</b> As people attain more wealth, people tend to want even more. This is the discontentment that causes unhappiness. Here contentment simply implies not being greedy and constantly desiring more. When one has attained contentment, one will always be wealthy, because one is happy with what one has.</p>
			<p><b>"To persist is to have inspiration."</b> It is important to realize the profound nature of the Dao; it is even more important to actively engage in the attainment of the Dao. The higher the goal, the more obstacles will be encountered on the path. If we give up because of obstacles, we will lose all the effort we put forth. It is necessary to continually work on the attainment of the Dao. It is through this persistence that one will achieve the goal, and this persistence is one's true inspiration.</p>
			<p><b>"Not deviating from the Dao is everlasting."</b> All things in the Great Cosmos came from the Dao. Humans live in an oxygen rich environment; if we lose oxygen, we will die. Fishes born in water need water; if they leave water, they will die. Trees grow on earth; if you pull them away from the ground, they will die. Because we live in the natural patterns of the Dao, we must adhere to the principles of the Dao to survive. Deviating from the Dao will result in premature deterioration.</p>
			<p><b>"Death without perishing is longevity."</b> True longevity is the continuation of the spirit after the physical body has died. We live and we die, this is the norm. Don't be sad or worry. What is important is to establish the true value of existence - the continuation of the spirit. Only the spirit that has united with the Dao is everlasting.</p>
			<p align="center"><img src="../../images/newsletter/v5n4/a2p1.jpg" width="500" height="263" border="0" alt="Expanding and Contracting Abdomen" align="right" style="margin-left:10px;"></p>
			<h3>Expanding and Contracting Abdomen</h3>
			<p><b>Movement:</b> Stand comfortably. Place your hands in front of your abdomen with your palms facing each other, fingers naturally apart, relax your shoulders and elbows (Figure 2-3).</p>
			<p>Inhale as you draw your abdomen in, touch the tip of your tongue gently on the palate of your mouth, and gradually pull your palms away form each other. Exhale as you push your abdomen out slightly, press your tongue gently on the bottom of your mouth, and gradually return your palms to the starting position (Figure 2-4 and Drawing 2-7). Repeat 21 times.</p>
		</article>
      </div>
    </div>
  </div>
</div>

<?php include "../../ssi/footer.php"; ?>

</body>

</html>