<!DOCTYPE html>

<?php
$globalNavId = "newsletters";
?>

<html lang="en">

<head>
<meta name="keywords" content="Daoist Qigong, Daoist View, Cosmos, Spirit, Grandmaster Shou-Yu Liang, Master Wen-Ching Wu" />
<meta name="description" content="Daoist Qigong - Daoist View of the Cosmos and Spirit, By Grandmaster Shou-Yu Liang and Master Wen-Ching Wu" />
<title>Daoist Qigong - Daoist View of the Cosmos and Spirit - shouyuliang.com</title>
<?php include "../../ssi/meta.php"; ?>
</head>

<body>

<?php include "../../ssi/header.php"; ?>

<div id="syl-body-bkg">
  <div id="syl-body">
    <div id="syl-body1">
      <div class="contentWidth clearfix">
        <nav id="syl-breadcrumb" class="breadcrumbs pathway">
          	<a href="/" class="pathway">Home</a> <img src="/templates/syl/images/arrow.png" /> <a href="/newsletters/" class="pathway">Articles</a> <img src="/templates/syl/images/arrow.png" /> <a href="index.php" class="pathway">2005 September/October</a> <img src="../../templates/syl/images/arrow.png" /> Daoist Qigong - Daoist View of the Cosmos and Spirit
        </nav>
		<article>
	        <h1 class="contentheading">Daoist Qigong - Daoist View of the Cosmos and Spirit</h1>
	        <h2>By Grandmaster Shou-Yu Liang and Master Wen-Ching Wu</h2>
	        <br><br>
			<h3>Daoist View of the Cosmos and Spirit - Food for Thought</h3>
			<img src="../../images/newsletter/v5n5/a2p1.jpg" width="113" height="171" border="0" alt="Taoist View">
			<p>There are controversial and superstitious beliefs in Daoism, just as there are in other philosophies in the world today. It is unwise to accept any philosophy blindly. It is just as unwise to dismiss any belief just because we do not understand it and modern science is unable to verify it yet. We should maintain an earnest effort to repeatedly experience and verify what we know and that which we are unfamiliar with.</p>
			<p>Daoists believe the cosmos includes Three Planes: the Lower, Middle, and Upper Planes. The Lower Plane consists of 6 levels, and is also referred to as the Six Physical Levels. These levels are visible to the human eye, consists of all physical forms, desires, senses, emotions, yin and yang are interacting, and humans are reborn. The Middle Plane consists of 18 levels, and is also referred to as the Eighteen Sensory Levels. The Middle Plane is visible to the human eye; consists of senses but no desire; no yin and yang interaction; and spirit is able to evolve. The Upper Plane consists of 4 levels, and is also referred to as the Four Mental Levels. These levels are not visible to the human eye and there is no physical forms or senses, only pure mentality.</p>
			<p>Within the Three Planes, there are a total of 28 levels. Beyond the Three Planes there are Four Enlightened Levels and Four Infinite Levels. The Four Infinite Levels are what is referred to as the Grand Purity Level, the Great Grand Purity Level, the Jade Purity Level, and the Final Level. There are a combined total of 36 levels that the spirit needs to evolve, before it is reunited with the Dao.</p>
			<p>The Dao is the regulator of all levels. The Upper Plane also regulates the Middle and the Lower Planes, and the Middle Plane regulates the Lower Plane. The evolution of the spirit differs in different planes. Qualitative evolution must be completed before the spirit is able to move up to the higher planes.</p>
			<p>There are other philosophies and religions that have similar beliefs. Buddhism is one of them. Daoists and Buddhists have mutually influenced each other over the millenniums. Therefore there are many similarities in their philosophies. Buddhist philosophy also views the cosmos to have the Physical, Sensory, and Mental Planes. In Buddhism, the Sensory Plane alone consists of 33 levels, and the Mental Plane consists of 18 levels. Also, within each of the levels are many sublevels. They also believe that there are an infinite amount of cosmos, planes, and levels.</p>
			<p>Yet, another philosophy views the cosmos as consisting of 7 planes. They are the Physical Plane, the Lower Astral Plane, the Upper Astral Plane, the Causal Plane, the Mental Plane, the Buddhic Plane, and the Dao. Within each one of these Planes are 7 levels. The Physical Plane includes all material substances, organic and inorganic. Everything that is visible to the human eye is in the Physical Plane. This includes all living and nonliving matters in the cosmos. The Lower Astral Plane includes spirits traveling to it from the Physical Plane, usually during meditation or in a dream state. It is also inhabited by those spirits that are between bodies, and spirits that are trying to complete their final karma without being reborn in the physical body. It also includes spirits that are partially reunited with each other as the spirits evolve and are closer to the Dao, they unite with other spirits as they work towards the ultimate unification with the Dao.</p>
			<p>Where did the Daoist and Buddhist and other spiritual beliefs derive their philosophy? Modern science is still unable to verify these beliefs. However, the similarity between their believes are striking. There are many books written in the English language on this subject. These books include the research and records of hypnotic healing, out of body experiences, research on unidentified flying objects, and the space exploration of astronauts and satellites. Many of these beliefs and observations are not yet verified by modern science, but they coincide with ancient Daoist and Buddhist beliefs.</p>
			<p>Daoism believes the human spirit consist of two components, the Original Spirit and the Personality (Post-Birth Spirit). Prior to the birth of a baby, a Spiritual Luminance enters the womb. The Combination of the Spiritual Luminance, the innate-qi, and innate jing results in the Original Spirit. The Original Spirit contains knowledge learned from numerous other lifetimes about the Ruth of the cosmos, and higher potentials. It is stored in the deep consciousness. Original Spirit appears as light, and has multiple colors. The Personality includes the learning and experience in this lifetime. It has an overshadowing and suppressing effect on the Original Spirit.</p>
			<p>Our Original Spirit contains information from numerous past lifetimes. Our Personality only contains information we learned in this lifetime. Original Spirit is hundreds of thousands of times wiser than our Personality. Through training we will allow the Original Spirit to emerge. Our Original Spirit can enter the astral planes (fourth and higher dimensions). When Original Spirit enters the astral planes, it can receive the teachings and help from Spiritual Guides and attain higher wisdom.</p>
			<p>Both Daoists and Traditional Chinese Medicine believe that humans consist of three finer spirits and seven baser spirits, together they animate the human body. The three finer spirits are classified as yang and the seven baser spirits are classified as yin. The cultivation of the spirit in Daoist training is to cultivate the three finer spirits to become Yang Spirit and the seven baser spirits to become Yin Spirit. The combination of the Yin Spirit and the Yang Spirit is the Original Spirit. Further cultivation combines the Original Spirit with the Dao.</p>
			<p>The astral travels of the Original Spirit is not the same as an out of body experience. Most out of body experience are usually that of the Yin Spirit leaving the body when individuals are sleeping, are ill and weak, and sometimes during early stages of qigong training. The Yin Spirit can easily be affected and attacked by ghosts on the lower astral planes, as well as, one's own negative Personality. The astral travels of the Yin Spirit are usually confined to the lower astral planes. When the Yang Spirit astral travels, it travels up to the higher astral planes. It does not float around.</p>
			<p>When the Original Spirit astral travels, it leaves the body through the baihui point, belly button, and other spiritual connection points on the body. Its travels are far and extensive, as it receives the guidance and teachings of the Spiritual Guides, to attain Great Wisdom, and continue the evolution of the spirit. When the Original Spirit is no longer regulated by yin-yang and the Five Elements of the Lower Plane, it will be able to achieve swift and enormous evolution. The wisdom and pure essence brought back to the physical body by the Original Spirit are also beneficial to the body, and sets a solid foundation for immortality. This type of spirit evolution process is much greater than going through countless reincarnations.</p>
			<p>In the cultivation to become one with the Dao, high level qigong achievers also attain many extraordinary abilities or Spiritual Connections. These abilities include clairvoyance, clairaudience, telepathy, precognition/regression, teleportation, and immortality. Spiritual Connections are either a by product of one's spiritual evolution or channeled. Throughout the many dynasties in China, many highly accomplished Daoist masters were known to have attained longevity and were able to do extraordinary and mystical tasks. Their Spiritual Connections were a prelude to attaining the Dao.</p>
			<p>Spiritual Connections are innate within humans and animals. The question is whether or not, one is able to bring about this potential with proper cultivation. It is easier to bring about this potential when one is young and before one's Personality completely overshadows their Original Spirit. From ancient times until today, there have been many sages, religious leaders, preachers, and psychics who all have a very strong potential and extraordinary abilities. Their abilities are the by-product of the evolution of their spirit, not the goal they sought. Throughout history, the masters of old cautioned students not to seek these extraordinary abilities. When one has evolved to have these abilities, one must use them with caution, use them sparsely, and best not to use them at all. They are not to be used for demonstrations.</p>
			<p>The only way to continue to evolve to higher levels is to continue cultivating one's spirit. The extraordinary abilities of gifted young people that are not derived from cultivation, are usually unstable. If they don't train their body, qi, and cultivate their spirit, they will deplete their innate jing and innate-qi. Without the support of these vital substances, their abilities will gradually decrease and vanish.</p>
			<p>Some individuals are able to channel Spiritual Connections. These individuals have achieved a definite qigong foundation. They can use specific channeling methods to acquire the assistance of Spiritual Guides. They use sym bols, incantations, mantras, and/or prayers to procure the assistance of Spiritual Guides to produce miraculous effects. Daoist priests often use channeling to attain Spiritual Connections for eliminating misfortune, to bring good luck and fortune, and to heal the sick. They also help others to release pent-up grief, to accumulate Virtue, and cultivate the Dao.</p>
			<p>Similar to many other channels in different parts of the world, Daoist priests also ask Spiritual Guides to manifest in their body, to help them resolve problems. If, however, the invited Spiritual Guide is not a highly evolved spirit, the extraordinary abilities will not be able to occur. This is especially apparent when channeling is done in temples, churches, or in the presence of priests and individuals with a very strong potential and spirit evolution themselves. The leader of a nation, head of a religion, high priests, high lamas, highly achieved qigong cultivator, and individuals that steadily walk on the righteous path all have a very strong inner potential. Their inner potential can also prevent bad influences from affecting them.</p>
			<p>Their is a famous saying, "High level Daoists cultivate the spirit, middle level Daoists cultivate the qi, and lower level Daoists cultivate the jing." Jing and qi are the material foundation for the spirit. They are also the activation force for the spirit. They are like the fuel in your car, if you drive recklessly and waste fuel with bad driving habits, your gas mileage will be reduced and you will not be able to go as far. Wastefulness will prevent your spirit from reaching the next, more wonderful destination.</p>
		</article>
      </div>
    </div>
  </div>
</div>

<?php include "../../ssi/footer.php"; ?>

</body>

</html>